/**
 * This file is AUTO GENERATED by [msw-auto-mock](https://github.com/zoubingwu/msw-auto-mock)
 * Feel free to commit/edit it as you need.
 */
/* eslint-disable */
/* tslint:disable */
import { HttpResponse, http } from 'msw';
import { faker } from '@faker-js/faker';

faker.seed(1);

const baseURL = '';
const MAX_ARRAY_LENGTH = 20;

let i = 0;
const next = () => {
  if (i === Number.MAX_SAFE_INTEGER - 1) {
    i = 0;
  }
  return i++;
};

export const handlers = [
  http.get(`${baseURL}/areas/hierarchies`, async () => {
    const resultArray = [
      [await getGetAreaHierarchies200Response(), { status: 200 }],
      [await getGetAreaHierarchies500Response(), { status: 500 }],
    ];

    return HttpResponse.json(...resultArray[next() % resultArray.length]);
  }),
  http.get(`${baseURL}/areas/areatypes`, async () => {
    const resultArray = [
      [await getGetAreaTypes200Response(), { status: 200 }],
      [await getGetAreaTypes500Response(), { status: 500 }],
    ];

    return HttpResponse.json(...resultArray[next() % resultArray.length]);
  }),
  http.get(`${baseURL}/areas/:areaCode`, async () => {
    const resultArray = [
      [await getGetArea200Response(), { status: 200 }],
      [await getGetArea400Response(), { status: 400 }],
      [await getGetArea500Response(), { status: 500 }],
    ];

    return HttpResponse.json(...resultArray[next() % resultArray.length]);
  }),
  http.get(`${baseURL}/areas/root`, async () => {
    const resultArray = [
      [await getGetAreaRoot200Response(), { status: 200 }],
      [await getGetAreaRoot500Response(), { status: 500 }],
    ];

    return HttpResponse.json(...resultArray[next() % resultArray.length]);
  }),
  http.get(`${baseURL}/indicators`, async () => {
    const resultArray = [
      [await getFilterIndicators200Response(), { status: 200 }],
      [await getFilterIndicators400Response(), { status: 400 }],
      [await getFilterIndicators500Response(), { status: 500 }],
    ];

    return HttpResponse.json(...resultArray[next() % resultArray.length]);
  }),
  http.get(`${baseURL}/indicators/:indicatorId`, async () => {
    const resultArray = [
      [await getGetIndicator200Response(), { status: 200 }],
      [await getGetIndicator404Response(), { status: 404 }],
      [await getGetIndicator500Response(), { status: 500 }],
    ];

    return HttpResponse.json(...resultArray[next() % resultArray.length]);
  }),
  http.get(`${baseURL}/indicators/:indicatorId/data`, async () => {
    const resultArray = [
      [await getGetHealthDataForAnIndicator200Response(), { status: 200 }],
      [await getGetHealthDataForAnIndicator400Response(), { status: 400 }],
      [await getGetHealthDataForAnIndicator500Response(), { status: 500 }],
    ];

    return HttpResponse.json(...resultArray[next() % resultArray.length]);
  }),
];

export function getGetAreaHierarchies200Response() {
  return [
    ...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys(),
  ].map((_) => faker.lorem.words());
}

export function getGetAreaHierarchies500Response() {
  return {
    message: faker.lorem.words(),
  };
}

export function getGetAreaTypes200Response() {
  return [
    ...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys(),
  ].map((_) => faker.lorem.words());
}

export function getGetAreaTypes500Response() {
  return {
    message: faker.lorem.words(),
  };
}

export function getGetArea200Response() {
  return {
    code: 'E06000047',
    name: 'County Durham',
    hierarchyName: 'NHS',
    areaType: 'PCN',
    level: '3',
    parent: {
      code: 'E06000047',
      name: 'County Durham',
      hierarchyName: 'NHS',
      areaType: 'PCN',
      level: '3',
    },
    children: [
      ...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys(),
    ].map((_) => ({
      code: 'E06000047',
      name: 'County Durham',
      hierarchyName: 'NHS',
      areaType: 'PCN',
      level: '3',
    })),
    siblings: [
      ...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys(),
    ].map((_) => ({
      code: 'E06000047',
      name: 'County Durham',
      hierarchyName: 'NHS',
      areaType: 'PCN',
      level: '3',
    })),
    cousins: [
      ...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys(),
    ].map((_) => ({
      code: 'E06000047',
      name: 'County Durham',
      hierarchyName: 'NHS',
      areaType: 'PCN',
      level: '3',
    })),
    ancestors: [
      ...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys(),
    ].map((_) => ({
      code: 'E06000047',
      name: 'County Durham',
      hierarchyName: 'NHS',
      areaType: 'PCN',
      level: '3',
    })),
  };
}

export function getGetArea400Response() {
  return {
    message: faker.lorem.words(),
  };
}

export function getGetArea500Response() {
  return {
    message: faker.lorem.words(),
  };
}

export function getGetAreaRoot200Response() {
  return {
    code: 'E92000001',
    name: 'England',
  };
}

export function getGetAreaRoot500Response() {
  return {
    message: faker.lorem.words(),
  };
}

export function getFilterIndicators200Response() {
  return [
    ...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys(),
  ].map((_) => ({
    indicator_id: 3456,
    title: 'Hypertension: QOF prevalence (all ages)',
  }));
}

export function getFilterIndicators400Response() {
  return {
    message: faker.lorem.words(),
  };
}

export function getFilterIndicators500Response() {
  return {
    message: faker.lorem.words(),
  };
}

export function getGetIndicator200Response() {
  return {
    indicator_id: 3456,
    title: 'Hypertension: QOF prevalence (all ages)',
    definition:
      'The percentage of patients with established hypertension, as recorded on practice disease registers (proportion of total list size)',
  };
}

export function getGetIndicator404Response() {
  return {
    message: faker.lorem.words(),
  };
}

export function getGetIndicator500Response() {
  return {
    message: faker.lorem.words(),
  };
}

export function getGetHealthDataForAnIndicator200Response() {
  return [
    ...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys(),
  ].map((_) => ({
    areaCode: 'A1426',
    areaName: 'Scarfolk Medical Center',
    healthData: [
      ...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys(),
    ].map((_) => ({
      year: 2023,
      count: 222,
      value: 506.60912,
      lowerCi: 441.69151,
      upperCi: 578.32766,
      ageBand: '0-4',
      sex: 'Female',
    })),
  }));
}

export function getGetHealthDataForAnIndicator400Response() {
  return {
    message: faker.lorem.words(),
  };
}

export function getGetHealthDataForAnIndicator500Response() {
  return {
    message: faker.lorem.words(),
  };
}
