/* tslint:disable */
/* eslint-disable */
/**
 * Fingertips API
 * An API to query public health indicator data.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ProfileFeedback@dhsc.gov.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Details of the age band that this data point belongs to.
 * @export
 * @interface AgeData
 */
export interface AgeData {
    /**
     * Age band which the data are for.
     * @type {string}
     * @memberof AgeData
     */
    value: string;
    /**
     * Indicates if the datapoint is an aggregated value for the age dimension.
     * @type {boolean}
     * @memberof AgeData
     */
    isAggregate: boolean;
}

/**
 * Check if a given object implements the AgeData interface.
 */
export function instanceOfAgeData(value: object): value is AgeData {
    if (!('value' in value) || value['value'] === undefined) return false;
    if (!('isAggregate' in value) || value['isAggregate'] === undefined) return false;
    return true;
}

export function AgeDataFromJSON(json: any): AgeData {
    return AgeDataFromJSONTyped(json, false);
}

export function AgeDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgeData {
    if (json == null) {
        return json;
    }
    return {
        
        'value': json['value'],
        'isAggregate': json['isAggregate'],
    };
}

export function AgeDataToJSON(json: any): AgeData {
    return AgeDataToJSONTyped(json, false);
}

export function AgeDataToJSONTyped(value?: AgeData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'value': value['value'],
        'isAggregate': value['isAggregate'],
    };
}

