/* tslint:disable */
/* eslint-disable */
/**
 * Fingertips API
 * An API to query public health indicator data.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ProfileFeedback@dhsc.gov.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetHealthcheck200Response
 */
export interface GetHealthcheck200Response {
    /**
     * 
     * @type {string}
     * @memberof GetHealthcheck200Response
     */
    status?: string;
}

/**
 * Check if a given object implements the GetHealthcheck200Response interface.
 */
export function instanceOfGetHealthcheck200Response(value: object): value is GetHealthcheck200Response {
    return true;
}

export function GetHealthcheck200ResponseFromJSON(json: any): GetHealthcheck200Response {
    return GetHealthcheck200ResponseFromJSONTyped(json, false);
}

export function GetHealthcheck200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetHealthcheck200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function GetHealthcheck200ResponseToJSON(json: any): GetHealthcheck200Response {
    return GetHealthcheck200ResponseToJSONTyped(json, false);
}

export function GetHealthcheck200ResponseToJSONTyped(value?: GetHealthcheck200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
    };
}

