services:
  frontend:
    profiles:
      - all
      - app-services
      - frontend

    build: frontend/fingertips-frontend
    environment:
      FINGERTIPS_API_URL: "http://api:8080"
      DHSC_AI_SEARCH_USE_MOCK_SERVICE: true
      NEXT_PUBLIC_FINGERTIPS_GIT_HASH: ${NEXT_PUBLIC_FINGERTIPS_GIT_HASH}
      NEXT_PUBLIC_FINGERTIPS_GIT_TAG: ${NEXT_PUBLIC_FINGERTIPS_GIT_TAG}
      AUTH_SECRET: ${AUTH_SECRET}
      AUTH_ISSUER: ${AUTH_ISSUER}
      AUTH_WELLKNOWN: ${AUTH_WELLKNOWN}
      AUTH_CLIENT_ID: ${AUTH_CLIENT_ID}
      AUTH_CLIENT_SECRET: ${AUTH_CLIENT_SECRET}
      AUTH_TRUST_HOST: true
      AUTH_URL: "http://localhost:3000/auth"
      AUTH_USE_PASSWORD_MOCK: ${AUTH_USE_PASSWORD_MOCK}

    ports:
      - 3000:3000

  api:
    profiles:
      - all
      - app-services
      - api

    depends_on:
      db:
        condition: service_completed_successfully
      storage-setup:
        condition: service_completed_successfully

    build: api
    environment:
      DB_SERVER: db
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      TRUST_CERT: "True"
      # These are the publicly-available connection details for the Azurite storage emulator.
      # DO NOT commit the details of an actual Azure Storage account here!
      UPLOAD_STORAGE_ACCOUNT_URI: "${UPLOAD_STORAGE_ACCOUNT_URI:-http://storage:10000/devstoreaccount1}"
      UPLOAD_STORAGE_ACCOUNT_NAME: "${UPLOAD_STORAGE_ACCOUNT_NAME:-devstoreaccount1}"
      UPLOAD_STORAGE_ACCOUNT_KEY: "${UPLOAD_STORAGE_ACCOUNT_KEY:-Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==}"
      UPLOAD_STORAGE_CONTAINER_NAME: ${UPLOAD_STORAGE_CONTAINER_NAME}
      AzureAD__Instance: ${AZUREAD__INSTANCE}
      AzureAD__TenantId: ${AZUREAD__TENANTID}
      AzureAD__ClientId: ${AZUREAD__CLIENTID}
      Graph__Scopes: "User.Read"
      AUTHENTICATION__SCHEMES__BEARER__VALIDAUDIENCES__0 : "http://localhost:8080"
      AUTHENTICATION__SCHEMES__BEARER__VALIDAUDIENCES__1 : "http://localhost:5144"
      AUTHENTICATION__SCHEMES__BEARER__VALIDISSUER: "dotnet-user-jwts"
      AUTHENTICATION__SCHEMES__BEARER__SIGNINGKEYS__0__ID : "88a400e7"
      AUTHENTICATION__SCHEMES__BEARER__SIGNINGKEYS__0__ISSUER: "dotnet-user-jwts"
      AUTHENTICATION__SCHEMES__BEARER__SIGNINGKEYS__0__VALUE : ${JWTS_SIGNING_KEY}
      AUTHENTICATION__SCHEMES__BEARER__SIGNINGKEYS__0__LENGTH: 32

    ports:
      - 5144:8080
    healthcheck:
      test: curl -f http://localhost:8080/healthcheck
      interval: 15s
      timeout: 5s
      retries: 15
      start_period: 60s

  db:
    profiles:
      - all
      - api
      - backend-services
      - db

    image: mcr.microsoft.com/mssql/server
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${DB_PASSWORD}
    ports:
      - 1433:1433
    volumes:
      - ./DataCreator/DataCreator/data/out:/var/opt/mssql/csv/
      - ./DataCreator/DataCreator/data/environment/dev/indicatorroles.csv:/var/opt/mssql/csv/indicatorroles.csv

  storage:
    profiles:
      - all
      - api
      - backend-services
      - storage

    image: mcr.microsoft.com/azure-storage/azurite
    command:
      - azurite-blob # Run only the blob storage service
      - --blobHost # Allow the blob service to listen for external connections
      - 0.0.0.0
      - --skipApiVersionCheck # Don't enforce specific API versions
    ports:
      - 10000:10000

  storage-setup:
    profiles:
      - all
      - api
      - backend-services
      - storage

    depends_on:
      - storage

    image: mcr.microsoft.com/azure-cli
    command:
      - az
      - storage
      - container
      - create
      - --blob-endpoint
      # These are the publicly-available connection details for the Azurite storage emulator.
      # DO NOT commit the details of an actual Azure Storage account here!
      - "${UPLOAD_STORAGE_ACCOUNT_URI:-http://storage:10000/devstoreaccount1}"
      - --account-name
      - "${UPLOAD_STORAGE_ACCOUNT_NAME:-devstoreaccount1}"
      - --account-key
      - "${UPLOAD_STORAGE_ACCOUNT_KEY:-Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==}"
      - --name
      - ${UPLOAD_STORAGE_CONTAINER_NAME}
