
### check GET all area types

GET http://localhost:5144/areas/areatypes

> {%
    client.test("Expected area types returned", function (callbackfn, thisArg) {
        const expected = [
            {
                "key": "combined-authorities",
                "name": "Combined Authorities",
                "hierarchyName": "Administrative",
                "level": 2
            },
            {
                "key": "counties-and-unitary-authorities",
                "name": "Counties and Unitary Authorities",
                "hierarchyName": "Administrative",
                "level": 3
            },
            {
                "key": "districts-and-unitary-authorities",
                "name": "Districts and Unitary Authorities",
                "hierarchyName": "Administrative",
                "level": 4
            },
            {
                "key": "england",
                "name": "England",
                "hierarchyName": "Both",
                "level": 1
            },
            {
                "key": "gps",
                "name": "GPs",
                "hierarchyName": "NHS",
                "level": 6
            },
            {
                "key": "nhs-integrated-care-boards",
                "name": "NHS Integrated Care Boards",
                "hierarchyName": "NHS",
                "level": 3
            },
            {
                "key": "nhs-primary-care-networks",
                "name": "NHS Primary Care Networks",
                "hierarchyName": "NHS",
                "level": 5
            },
            {
                "key": "nhs-regions",
                "name": "NHS Regions",
                "hierarchyName": "NHS",
                "level": 2
            },
            {
                "key": "nhs-sub-integrated-care-boards",
                "name": "NHS Sub Integrated Care Boards",
                "hierarchyName": "NHS",
                "level": 4
            },
            {
                "key": "regions",
                "name": "Regions",
                "hierarchyName": "Administrative",
                "level": 2
            }
        ].sort((at1, at2) => {
            if(at1.level === at2.level) return 0;
            if(at1.level < at2.level) return -1;
            return 1;
        });
        
        client.assert(response.status === 200, "Response status is not 200");

        let returnedTypes = response.body
        client.assert(returnedTypes.length === expected.length);
        returnedTypes.sort((at1, at2) => {
            if(at1.level === at2.level) return 0;
            if(at1.level < at2.level) return -1;
            return 1;
        })

        client.assert(JSON.stringify(returnedTypes) === JSON.stringify(expected));
    });
%}



### check GET NHS area types

GET http://localhost:5144/areas/areatypes?hierarchy_type=NHS

> {%
    client.test("Expected NHS area types returned", function (callbackfn, thisArg) {
        const expected = [
            "england",
            "gps",
            "nhs-integrated-care-boards",
            "nhs-primary-care-networks",
            "nhs-regions",
            "nhs-sub-integrated-care-boards"
        ];
        client.assert(response.status === 200, "Response status is not 200");

        let returnedTypes = response.body
        client.assert(returnedTypes.length === expected.length);
        returnedTypes.forEach(r => client.assert(expected.find(e => e === r.key) != null))
    });
%}

###