
GET http://localhost:5144/areas/hierarchies

> {%
    client.test("Three area hierarchies expected", function() {
        client.assert(response.status === 200, "Response status is not 200");
        
        client.assert(response.body.length === 2, "two hierarchies expected")
        client.assert(response.body.find(element => element === 'Administrative') != null, "Administrative hierarchy missing")
        client.assert(response.body.find(element => element === 'NHS') != null, "NHS hierarchy missing")
    });
%}
