{{+
    const { execSync } = require('child_process');
    const  path  = require('node:path');
    
    const fileDir = path.join(__dirname, '..', 'DHSC.FingertipsNext.Api');

    var token = execSync('dotnet user-jwts create -o token', { cwd: fileDir }).toString();

  // the *entire* stdout and stderr (buffered)
  console.log(token);

  exports.defaultHeaders = {
    'Authorization': `Bearer ${token}`
  };
}}
### Call authorised endpoint with a valid token and verify 200 ok response.
GET http://localhost:5144/user/info
> {%
  console.log(response);

    client.test("Expected authenticated endpoint returns authentication failure", function (callbackfn, thisArg) {
        client.assert(response.status === 200, "Authenticated response");
    });
%}

{{+
  exports.defaultHeaders = {
  };
}}
### Call authorised endpoint with a valid bearer token and verify 401 unauthorised response
GET http://localhost:5144/user/info
> {%
    client.test("Expected authenticated endpoint returns authentication failure", function (callbackfn, thisArg) {
        client.assert(response.status === 401, "Response status is not 200");
    });
%}