indicator_ids:
  in: query
  name: indicator_ids
  description: A list of indicator_ids, up to 10 can be requested
  style: form
  schema:
    type: array
    items:
      type: integer
      example: 1234
    maxItems: 10
indicator_id:
  in: path
  name: indicator_id
  style: simple
  schema:
    type: integer
    example: 1234
    minimum: 1
  explode: false
  required: true
  description: The unique identifier of the indicator
batch_id:
  in: path
  name: batch_id
  style: simple
  schema:
    type: string
    example: "12345_20250101120000"
  explode: false
  required: true
  description: The unique identifier of the batch of data
area_type:
  in: query
  name: area_type
  description: The area type which the areas belong to
  schema:
    type: string
ancestor_code:
  in: query
  name: ancestor_code
  description: An ancestor area which the area_codes belong to
  schema:
    type: string
    example: E38000205
latest_only:
  in: query
  name: latest_only
  description: Set to true to get data for the latest date period only, default is false. This overrides the years parameter if set to true.
  schema:
    type: boolean
benchmark_ref_type:
  in: query
  name: benchmark_ref_type
  description: The benchmark reference type
  schema:
    $ref: "./schemas.yaml#/BenchmarkReferenceType"
years:
  in: query
  name: years
  description: A list of years, up to 20 years can be requested
  style: form
  schema:
    type: array
    items:
      type: integer
      example: 2023
    maxItems: 20
to_date:
  in: query
  name: to_date
  description: The latest date, in ISO 8601 format (YYYY-MM-DD), for which data should be returned, if not specified then the latest date for the indicator will be used.
  schema:
    type: string
    example: '2023-12-31'
from_date:
  in: query
  name: from_date
  description: The earliest date, in ISO 8601 format (YYYY-MM-DD), for which data should be returned, if not specified then the earliest date for the indicator will be used.
  schema:
    type: string    
    example: '2023-01-01'
inequalities:
  in: query
  name: inequalities
  style: form
  schema:
    type: array
    items:
      type: string
      enum:
        - age
        - sex
        - deprivation
  description: Determines the kind of inequality data that should be returned if an option is specified