import {
  HealthDataForArea,
  HealthDataPointTrendEnum,
} from '@/generated-sources/ft-api-client';
import {
  allAgesAge,
  disaggregatedAge,
  femaleSex,
  maleSex,
  noDeprivation,
  personsSex,
} from '../mocks';

export const MOCK_ENGLAND_DATA: HealthDataForArea = {
  areaCode: 'E92000001',
  areaName: 'England',
  healthData: [
    {
      year: 2004,
      count: 200,
      value: 904.874,
      lowerCi: 0,
      upperCi: 0,
      ageBand: disaggregatedAge('0-4'),
      sex: personsSex,
      trend: HealthDataPointTrendEnum.NotYetCalculated,
      deprivation: noDeprivation,
    },
    {
      year: 2008,
      count: 500,
      value: 965.9843,
      lowerCi: 0,
      upperCi: 0,
      ageBand: disaggregatedAge('10-14'),
      sex: personsSex,
      trend: HealthDataPointTrendEnum.NotYetCalculated,
      deprivation: noDeprivation,
    },
  ],
};

export const MOCK_HEALTH_DATA: HealthDataForArea[] = [
  {
    areaCode: 'A1425',
    areaName: 'Greater Manchester ICB - 00T',
    healthData: [
      {
        year: 2008,
        count: 222,
        value: 890.305692,
        lowerCi: 441.69151,
        upperCi: 578.32766,
        ageBand: allAgesAge,
        sex: personsSex,
        trend: HealthDataPointTrendEnum.NotYetCalculated,
        deprivation: noDeprivation,
        isAggregate: true,
      },
      {
        year: 2004,
        count: 267,
        value: 703.420759,
        lowerCi: 441.69151,
        upperCi: 578.32766,
        ageBand: allAgesAge,
        sex: personsSex,
        trend: HealthDataPointTrendEnum.NotYetCalculated,
        deprivation: noDeprivation,
        isAggregate: true,
      },
      {
        year: 2004,
        count: 267,
        value: 703.420759,
        lowerCi: 441.69151,
        upperCi: 578.32766,
        ageBand: allAgesAge,
        sex: maleSex,
        trend: HealthDataPointTrendEnum.NotYetCalculated,
        deprivation: noDeprivation,
        isAggregate: false,
      },
      {
        year: 2004,
        count: 267,
        value: 703.420759,
        lowerCi: 441.69151,
        upperCi: 578.32766,
        ageBand: allAgesAge,
        sex: femaleSex,
        trend: HealthDataPointTrendEnum.NotYetCalculated,
        deprivation: noDeprivation,
        isAggregate: false,
      },
    ],
  },
  {
    areaCode: 'A1426',
    areaName: 'South FooBar',
    healthData: [
      {
        year: 2008,
        count: 222,
        value: 135.149304,
        lowerCi: 441.69151,
        upperCi: 578.32766,
        ageBand: allAgesAge,
        sex: personsSex,
        trend: HealthDataPointTrendEnum.NotYetCalculated,
        deprivation: noDeprivation,
        isAggregate: true,
      },
      {
        year: 2008,
        count: 131,
        value: 890.328253,
        lowerCi: 441.69151,
        upperCi: 578.32766,
        ageBand: allAgesAge,
        sex: maleSex,
        trend: HealthDataPointTrendEnum.NotYetCalculated,
        deprivation: noDeprivation,
        isAggregate: false,
      },
      {
        year: 2008,
        count: 131,
        value: 890.328253,
        lowerCi: 441.69151,
        upperCi: 578.32766,
        ageBand: allAgesAge,
        sex: femaleSex,
        trend: HealthDataPointTrendEnum.NotYetCalculated,
        deprivation: noDeprivation,
        isAggregate: false,
      },
      {
        year: 2004,
        count: 131,
        value: 890.328253,
        lowerCi: 441.69151,
        upperCi: 578.32766,
        ageBand: allAgesAge,
        sex: femaleSex,
        trend: HealthDataPointTrendEnum.NotYetCalculated,
        deprivation: noDeprivation,
        isAggregate: false,
      },
    ],
  },
];

export const MOCK_PARENT_DATA: HealthDataForArea = {
  areaCode: 'E40000014',
  areaName: 'NHS North West Region',
  healthData: [
    {
      year: 2008,
      count: 777,
      value: 1000,
      lowerCi: 500,
      upperCi: 1500,
      ageBand: allAgesAge,
      sex: personsSex,
      trend: HealthDataPointTrendEnum.NotYetCalculated,
      deprivation: noDeprivation,
    },
    {
      year: 2004,
      count: 777,
      value: 1000,
      lowerCi: 500,
      upperCi: 1500,
      ageBand: allAgesAge,
      sex: personsSex,
      trend: HealthDataPointTrendEnum.NotYetCalculated,
      deprivation: noDeprivation,
    },
  ],
};

export const GROUPED_YEAR_DATA = {
  2004: {
    Male: [MOCK_HEALTH_DATA[0].healthData[2]],
    Female: [MOCK_HEALTH_DATA[0].healthData[3]],
    Persons: [],
  },
  2008: {
    Persons: [MOCK_HEALTH_DATA[1].healthData[0]],
    Male: [MOCK_HEALTH_DATA[1].healthData[1]],
    Female: [MOCK_HEALTH_DATA[1].healthData[2]],
  },
};

export const MOCK_HEALTH_DATA_WITH_TRENDS: HealthDataForArea[] = [
  {
    areaCode: '1472',
    areaName: 'Manchester - Counties and Unitary Authorities',
    healthData: [
      {
        year: 2019,
        count: 1400,
        value: 222.305692,
        lowerCi: 220.69151,
        upperCi: 224.32766,
        ageBand: allAgesAge,
        sex: personsSex,
        trend: HealthDataPointTrendEnum.NotYetCalculated,
        deprivation: noDeprivation,
      },
      {
        year: 2022,
        count: 1400,
        value: 222.305692,
        lowerCi: 220.69151,
        upperCi: 224.32766,
        ageBand: allAgesAge,
        sex: personsSex,
        trend: HealthDataPointTrendEnum.NotYetCalculated,
        deprivation: noDeprivation,
      },
      {
        year: 2023,
        count: 1400,
        value: 222.305692,
        lowerCi: 220.69151,
        upperCi: 224.32766,
        ageBand: allAgesAge,
        sex: personsSex,
        trend: HealthDataPointTrendEnum.NotYetCalculated,
        deprivation: noDeprivation,
      },
      {
        year: 2024,
        count: 1400,
        value: 222.305692,
        lowerCi: 220.69151,
        upperCi: 224.32766,
        ageBand: allAgesAge,
        sex: personsSex,
        trend: HealthDataPointTrendEnum.NoSignificantChange,
        deprivation: noDeprivation,
      },
    ],
  },
  {
    areaCode: 'A1426',
    areaName: 'South FooBar',
    healthData: [
      {
        year: 2019,
        count: 1400,
        value: 222.305692,
        lowerCi: 220.69151,
        upperCi: 224.32766,
        ageBand: allAgesAge,
        sex: personsSex,
        trend: HealthDataPointTrendEnum.NotYetCalculated,
        deprivation: noDeprivation,
      },
      {
        year: 2022,
        count: 1400,
        value: 222.305692,
        lowerCi: 220.69151,
        upperCi: 224.32766,
        ageBand: allAgesAge,
        sex: personsSex,
        trend: HealthDataPointTrendEnum.NotYetCalculated,
        deprivation: noDeprivation,
      },
      {
        year: 2023,
        count: 1566,
        value: 240.305692,
        lowerCi: 237.69151,
        upperCi: 245.32766,
        ageBand: allAgesAge,
        sex: personsSex,
        trend: HealthDataPointTrendEnum.NotYetCalculated,
        deprivation: noDeprivation,
      },
      {
        year: 2024,
        count: 1700,
        value: 260.305692,
        lowerCi: 258.69151,
        upperCi: 262.32766,
        ageBand: allAgesAge,
        sex: personsSex,
        trend: HealthDataPointTrendEnum.IncreasingAndGettingWorse,
        deprivation: noDeprivation,
      },
    ],
  },
];
