@BaseAddress = http://localhost:5144

### Successful test: check response status is 200
GET {{BaseAddress}}/core/forecast
Accept: application/json

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Successful test: Cross-module comms test - check response status is 200
GET {{BaseAddress}}/core/search-forecast?searchTerm=test
Accept: application/json

> {%
    client.test("Cross-module request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Successful test: Cross-module comms test - check response status is 200
GET {{BaseAddress}}/search?searchTerm=blah!
Accept: application/json

> {%
    client.test("Cross-module request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}