name: 'Reusable Terraform Unit Tests'

inputs:
  terraform_directory:
    description: 'The directory containing Terraform configuration files'
    required: true
    type: string
  terraform_vars:
    description: 'JSON object of Terraform variables (key-value pairs)'
    required: false
    type: string
  terraform_state_rg:
    description: 'Terraform state file resource group'
    required: true
    type: string
  terraform_state_storage_account:
    description: 'Terraform state file storage account'
    required: true
    type: string
  terraform_state_storage_container:
    description: 'Terraform state file storage container'
    required: true
    type: string
  terraform_state_key:
    description: 'Terraform state file name'
    required: true
    type: string
  github-token:
    description: 'GitHub token to comment on PR'
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      shell: bash
      working-directory: ${{ inputs.terraform_directory }}
      run: |
        terraform init -no-color \
          -backend-config="resource_group_name=${{ inputs.terraform_state_rg }}" \
          -backend-config="storage_account_name=${{ inputs.terraform_state_storage_account }}" \
          -backend-config="container_name=${{ inputs.terraform_state_storage_container }}" \
          -backend-config="key=${{ inputs.terraform_state_key }}"

    - name: Terraform Validate
      working-directory: ${{ inputs.terraform_directory }}
      shell: bash
      run: terraform validate -no-color

    - name: Terraform Format
      working-directory: ${{ inputs.terraform_directory }}
      shell: bash
      run: terraform fmt -check -recursive

    - name: Parse and Export Terraform Variables
      shell: bash
      id: export-vars
      run: |
        if [[ -n "${{ inputs.terraform_vars }}" ]]; then
          echo "Parsing Terraform variables..."
          echo '${{ inputs.terraform_vars }}' | jq -r 'to_entries | .[] | "\(.key)=\(.value)"' > variables.env
          cat variables.env >> $GITHUB_ENV
        else
          echo "No Terraform variables provided."
        fi

    - name: Terraform Plan
      working-directory: ${{ inputs.terraform_directory }}
      shell: bash
      id: tf-plan
      run: |
        export exitcode=0
        terraform plan -detailed-exitcode -no-color -out tfplan-${{ env.TF_VAR_container_name }} || export exitcode=$?

        echo "exitcode=$exitcode" >> $GITHUB_OUTPUT

        if [ $exitcode -eq 1 ]; then
          echo Terraform Plan Failed!
          exit 1
        else
          exit 0
        fi

    - name: Publish Terraform Plan
      uses: actions/upload-artifact@v4
      with:
        name: tfplan-${{ env.TF_VAR_container_name }}
        path: ${{ inputs.terraform_directory }}/tfplan-${{ env.TF_VAR_container_name }}

    - name: Create String Output
      shell: bash
      working-directory: ${{ inputs.terraform_directory }}
      id: tf-plan-string
      run: |
        TERRAFORM_PLAN=$(terraform show -no-color tfplan)

        delimiter="$(openssl rand -hex 8)"
        echo "summary<<${delimiter}" >> $GITHUB_OUTPUT
        echo "## Terraform Plan Output" >> $GITHUB_OUTPUT
        echo "<details><summary>Click to expand</summary>" >> $GITHUB_OUTPUT
        echo "" >> $GITHUB_OUTPUT
        echo '```terraform' >> $GITHUB_OUTPUT
        echo "$TERRAFORM_PLAN" >> $GITHUB_OUTPUT
        echo '```' >> $GITHUB_OUTPUT
        echo "</details>" >> $GITHUB_OUTPUT
        echo "${delimiter}" >> $GITHUB_OUTPUT

    - name: Publish Terraform Plan to Task Summary
      shell: bash
      env:
        SUMMARY: ${{ steps.tf-plan-string.outputs.summary }}
      run: |
        echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY

    - name: Push Terraform Output to PR
      uses: actions/github-script@v7
      env:
        SUMMARY: "${{ steps.tf-plan-string.outputs.summary }}"
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const body = `${process.env.SUMMARY}`;
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: body
          })
