/* tslint:disable */
/* eslint-disable */
/**
 * Fingertips API
 * An API to query public health indicator data.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ProfileFeedback@dhsc.gov.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetAreaHierarchies500Response
 */
export interface GetAreaHierarchies500Response {
    /**
     * 
     * @type {string}
     * @memberof GetAreaHierarchies500Response
     */
    message: string;
}

/**
 * Check if a given object implements the GetAreaHierarchies500Response interface.
 */
export function instanceOfGetAreaHierarchies500Response(value: object): value is GetAreaHierarchies500Response {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function GetAreaHierarchies500ResponseFromJSON(json: any): GetAreaHierarchies500Response {
    return GetAreaHierarchies500ResponseFromJSONTyped(json, false);
}

export function GetAreaHierarchies500ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAreaHierarchies500Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function GetAreaHierarchies500ResponseToJSON(json: any): GetAreaHierarchies500Response {
    return GetAreaHierarchies500ResponseToJSONTyped(json, false);
}

export function GetAreaHierarchies500ResponseToJSONTyped(value?: GetAreaHierarchies500Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

