/* tslint:disable */
/* eslint-disable */
/**
 * Fingertips API
 * An API to query public health indicator data.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ProfileFeedback@dhsc.gov.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetHealthcheck500Response
 */
export interface GetHealthcheck500Response {
    /**
     * 
     * @type {string}
     * @memberof GetHealthcheck500Response
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof GetHealthcheck500Response
     */
    message?: string;
}

/**
 * Check if a given object implements the GetHealthcheck500Response interface.
 */
export function instanceOfGetHealthcheck500Response(value: object): value is GetHealthcheck500Response {
    return true;
}

export function GetHealthcheck500ResponseFromJSON(json: any): GetHealthcheck500Response {
    return GetHealthcheck500ResponseFromJSONTyped(json, false);
}

export function GetHealthcheck500ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetHealthcheck500Response {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function GetHealthcheck500ResponseToJSON(json: any): GetHealthcheck500Response {
    return GetHealthcheck500ResponseToJSONTyped(json, false);
}

export function GetHealthcheck500ResponseToJSONTyped(value?: GetHealthcheck500Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'message': value['message'],
    };
}

