/* tslint:disable */
/* eslint-disable */
/**
 * Fingertips API
 * An API to query public health indicator data.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ProfileFeedback@dhsc.gov.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetUserInfo200Response
 */
export interface GetUserInfo200Response {
    /**
     * The external ID provided by the JWT authority.
     * @type {string}
     * @memberof GetUserInfo200Response
     */
    externalId?: string;
}

/**
 * Check if a given object implements the GetUserInfo200Response interface.
 */
export function instanceOfGetUserInfo200Response(value: object): value is GetUserInfo200Response {
    return true;
}

export function GetUserInfo200ResponseFromJSON(json: any): GetUserInfo200Response {
    return GetUserInfo200ResponseFromJSONTyped(json, false);
}

export function GetUserInfo200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUserInfo200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'externalId': json['externalId'] == null ? undefined : json['externalId'],
    };
}

export function GetUserInfo200ResponseToJSON(json: any): GetUserInfo200Response {
    return GetUserInfo200ResponseToJSONTyped(json, false);
}

export function GetUserInfo200ResponseToJSONTyped(value?: GetUserInfo200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'externalId': value['externalId'],
    };
}

