/* tslint:disable */
/* eslint-disable */
/**
 * Fingertips API
 * An API to query public health indicator data.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ProfileFeedback@dhsc.gov.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * a type of date period e.g. Calendar or Financial year.
 * @export
 */
export const PeriodType = {
    Calendar: 'Academic',
    Financial: 'Calendar',
    NovemberNovember: 'Financial',
    FinancialMultiYear: 'FinancialMultiYear',
    FinancialYearEndPoint: 'FinancialYearEndPoint',
    Yearly: 'Yearly',
    Unknown: 'Unknown'
} as const;
export type PeriodType = typeof PeriodType[keyof typeof PeriodType];


export function instanceOfPeriodType(value: any): boolean {
    for (const key in PeriodType) {
        if (Object.prototype.hasOwnProperty.call(PeriodType, key)) {
            if (PeriodType[key as keyof typeof PeriodType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PeriodTypeFromJSON(json: any): PeriodType {
    return PeriodTypeFromJSONTyped(json, false);
}

export function PeriodTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PeriodType {
    return json as PeriodType;
}

export function PeriodTypeToJSON(value?: PeriodType | null): any {
    return value as any;
}

export function PeriodTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): PeriodType {
    return value as PeriodType;
}

