/* tslint:disable */
/* eslint-disable */
/**
 * Fingertips API
 * An API to query public health indicator data.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: ProfileFeedback@dhsc.gov.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Represents a population data point with age band, total female, total male, percentage value female and percentage value male.
 * percentage value.
 * 
 * @export
 * @interface PopulationDataPoint
 */
export interface PopulationDataPoint {
    /**
     * 
     * @type {string}
     * @memberof PopulationDataPoint
     */
    ageBand: string;
    /**
     * total female population given age band
     * @type {number}
     * @memberof PopulationDataPoint
     */
    totalFemale: number;
    /**
     * total male population given age band
     * @type {number}
     * @memberof PopulationDataPoint
     */
    totalMale: number;
}

/**
 * Check if a given object implements the PopulationDataPoint interface.
 */
export function instanceOfPopulationDataPoint(value: object): value is PopulationDataPoint {
    if (!('ageBand' in value) || value['ageBand'] === undefined) return false;
    if (!('totalFemale' in value) || value['totalFemale'] === undefined) return false;
    if (!('totalMale' in value) || value['totalMale'] === undefined) return false;
    return true;
}

export function PopulationDataPointFromJSON(json: any): PopulationDataPoint {
    return PopulationDataPointFromJSONTyped(json, false);
}

export function PopulationDataPointFromJSONTyped(json: any, ignoreDiscriminator: boolean): PopulationDataPoint {
    if (json == null) {
        return json;
    }
    return {
        
        'ageBand': json['ageBand'],
        'totalFemale': json['totalFemale'],
        'totalMale': json['totalMale'],
    };
}

export function PopulationDataPointToJSON(json: any): PopulationDataPoint {
    return PopulationDataPointToJSONTyped(json, false);
}

export function PopulationDataPointToJSONTyped(value?: PopulationDataPoint | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ageBand': value['ageBand'],
        'totalFemale': value['totalFemale'],
        'totalMale': value['totalMale'],
    };
}

