/* tslint:disable */
/* eslint-disable */
/**
 * Fingertips API
 * An API to query public health indicator data.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: ProfileFeedback@dhsc.gov.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Represents a population data point with age band, total female, total male, percentage value female and percentage value male.
 * percentage value.
 * 
 * @export
 * @interface PopulationDataPoint
 */
export interface PopulationDataPoint {
    /**
     * 
     * @type {string}
     * @memberof PopulationDataPoint
     */
    ageBand: PopulationDataPointAgeBandEnum;
    /**
     * total female population given age band
     * @type {number}
     * @memberof PopulationDataPoint
     */
    totalFemale: number;
    /**
     * total male population given age band
     * @type {number}
     * @memberof PopulationDataPoint
     */
    totalMale: number;
    /**
     * percentage value female population given age band
     * @type {number}
     * @memberof PopulationDataPoint
     */
    valueFemale?: number;
    /**
     * percentage value male population given age band
     * @type {number}
     * @memberof PopulationDataPoint
     */
    valueMale?: number;
}


/**
 * @export
 */
export const PopulationDataPointAgeBandEnum = {
    _04: '0-4',
    _59: '5-9',
    _1014: '10-14',
    _1519: '15-19',
    _2024: '20-24',
    _2529: '25-29',
    _3034: '30-34',
    _3539: '35-39',
    _4044: '40-44',
    _4549: '45-49',
    _5054: '50-54',
    _5559: '55-59',
    _6064: '60-64',
    _6569: '65-69',
    _7074: '70-74',
    _7579: '75-79',
    _8084: '80-84',
    _8589: '85-89',
    _90: '90+'
} as const;
export type PopulationDataPointAgeBandEnum = typeof PopulationDataPointAgeBandEnum[keyof typeof PopulationDataPointAgeBandEnum];


/**
 * Check if a given object implements the PopulationDataPoint interface.
 */
export function instanceOfPopulationDataPoint(value: object): value is PopulationDataPoint {
    if (!('ageBand' in value) || value['ageBand'] === undefined) return false;
    if (!('totalFemale' in value) || value['totalFemale'] === undefined) return false;
    if (!('totalMale' in value) || value['totalMale'] === undefined) return false;
    return true;
}

export function PopulationDataPointFromJSON(json: any): PopulationDataPoint {
    return PopulationDataPointFromJSONTyped(json, false);
}

export function PopulationDataPointFromJSONTyped(json: any, ignoreDiscriminator: boolean): PopulationDataPoint {
    if (json == null) {
        return json;
    }
    return {
        
        'ageBand': json['age_band'],
        'totalFemale': json['total_female'],
        'totalMale': json['total_male'],
        'valueFemale': json['value_female'] == null ? undefined : json['value_female'],
        'valueMale': json['value_male'] == null ? undefined : json['value_male'],
    };
}

export function PopulationDataPointToJSON(json: any): PopulationDataPoint {
    return PopulationDataPointToJSONTyped(json, false);
}

export function PopulationDataPointToJSONTyped(value?: PopulationDataPoint | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'age_band': value['ageBand'],
        'total_female': value['totalFemale'],
        'total_male': value['totalMale'],
        'value_female': value['valueFemale'],
        'value_male': value['valueMale'],
    };
}

