/* tslint:disable */
/* eslint-disable */
/**
 * Fingertips API
 * An API to query public health indicator data.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: ProfileFeedback@dhsc.gov.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PopulationDataPoint } from './PopulationDataPoint';
import {
    PopulationDataPointFromJSON,
    PopulationDataPointFromJSONTyped,
    PopulationDataPointToJSON,
    PopulationDataPointToJSONTyped,
} from './PopulationDataPoint';

/**
 * Population data for a requested area
 * @export
 * @interface PopulationDataForArea
 */
export interface PopulationDataForArea {
    /**
     * The unique area code that the population data are for.
     * @type {string}
     * @memberof PopulationDataForArea
     */
    areaCode: string;
    /**
     * The name of the area code that the population data are for.
     * @type {string}
     * @memberof PopulationDataForArea
     */
    areaName: string;
    /**
     * The year which the population data are for.
     * @type {number}
     * @memberof PopulationDataForArea
     */
    year: number;
    /**
     * The unique identifier of the indicator
     * @type {number}
     * @memberof PopulationDataForArea
     */
    indicatorId: number;
    /**
     * The name of the indicator.
     * @type {string}
     * @memberof PopulationDataForArea
     */
    indicatorName: string;
    /**
     * The population data point for the area
     * @type {Array<PopulationDataPoint>}
     * @memberof PopulationDataForArea
     */
    populationData: Array<PopulationDataPoint>;
}

/**
 * Check if a given object implements the PopulationDataForArea interface.
 */
export function instanceOfPopulationDataForArea(value: object): value is PopulationDataForArea {
    if (!('areaCode' in value) || value['areaCode'] === undefined) return false;
    if (!('areaName' in value) || value['areaName'] === undefined) return false;
    if (!('year' in value) || value['year'] === undefined) return false;
    if (!('indicatorId' in value) || value['indicatorId'] === undefined) return false;
    if (!('indicatorName' in value) || value['indicatorName'] === undefined) return false;
    if (!('populationData' in value) || value['populationData'] === undefined) return false;
    return true;
}

export function PopulationDataForAreaFromJSON(json: any): PopulationDataForArea {
    return PopulationDataForAreaFromJSONTyped(json, false);
}

export function PopulationDataForAreaFromJSONTyped(json: any, ignoreDiscriminator: boolean): PopulationDataForArea {
    if (json == null) {
        return json;
    }
    return {
        
        'areaCode': json['areaCode'],
        'areaName': json['areaName'],
        'year': json['year'],
        'indicatorId': json['indicatorId'],
        'indicatorName': json['indicatorName'],
        'populationData': ((json['populationData'] as Array<any>).map(PopulationDataPointFromJSON)),
    };
}

export function PopulationDataForAreaToJSON(json: any): PopulationDataForArea {
    return PopulationDataForAreaToJSONTyped(json, false);
}

export function PopulationDataForAreaToJSONTyped(value?: PopulationDataForArea | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'areaCode': value['areaCode'],
        'areaName': value['areaName'],
        'year': value['year'],
        'indicatorId': value['indicatorId'],
        'indicatorName': value['indicatorName'],
        'populationData': ((value['populationData'] as Array<any>).map(PopulationDataPointToJSON)),
    };
}

