/* tslint:disable */
/* eslint-disable */
/**
 * Fingertips API
 * An API to query public health indicator data.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ProfileFeedback@dhsc.gov.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The root node of the area / geography hierarchies
 * @export
 * @interface RootArea
 */
export interface RootArea {
    /**
     * The unique area code of the area / geography
     * @type {string}
     * @memberof RootArea
     */
    code: string;
    /**
     * The name of the area / geography
     * @type {string}
     * @memberof RootArea
     */
    name: string;
}

/**
 * Check if a given object implements the RootArea interface.
 */
export function instanceOfRootArea(value: object): value is RootArea {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function RootAreaFromJSON(json: any): RootArea {
    return RootAreaFromJSONTyped(json, false);
}

export function RootAreaFromJSONTyped(json: any, ignoreDiscriminator: boolean): RootArea {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'name': json['name'],
    };
}

export function RootAreaToJSON(json: any): RootArea {
    return RootAreaToJSONTyped(json, false);
}

export function RootAreaToJSONTyped(value?: RootArea | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'name': value['name'],
    };
}

