/* tslint:disable */
/* eslint-disable */
/**
 * Fingertips API
 * An API to query public health indicator data.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ProfileFeedback@dhsc.gov.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Details of the sex category that this data point belongs to.
 * @export
 * @interface SexData
 */
export interface SexData {
    /**
     * Sex which the data are for.
     * @type {string}
     * @memberof SexData
     */
    value: string;
    /**
     * Indicates if the datapoint is an aggregated value for the sex dimension.
     * @type {boolean}
     * @memberof SexData
     */
    isAggregate: boolean;
}

/**
 * Check if a given object implements the SexData interface.
 */
export function instanceOfSexData(value: object): value is SexData {
    if (!('value' in value) || value['value'] === undefined) return false;
    if (!('isAggregate' in value) || value['isAggregate'] === undefined) return false;
    return true;
}

export function SexDataFromJSON(json: any): SexData {
    return SexDataFromJSONTyped(json, false);
}

export function SexDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): SexData {
    if (json == null) {
        return json;
    }
    return {
        
        'value': json['value'],
        'isAggregate': json['isAggregate'],
    };
}

export function SexDataToJSON(json: any): SexData {
    return SexDataToJSONTyped(json, false);
}

export function SexDataToJSONTyped(value?: SexData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'value': value['value'],
        'isAggregate': value['isAggregate'],
    };
}

