/* tslint:disable */
/* eslint-disable */
/**
 * Fingertips API
 * An API to query public health indicator data.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ProfileFeedback@dhsc.gov.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Representation of the currently logged in user
 * @export
 * @interface UserInfoType
 */
export interface UserInfoType {
    /**
     * An ID to uniquely identify the user. Currently mapped to the NameIdentifier claim within the JWT.
     * @type {string}
     * @memberof UserInfoType
     */
    externalId: string;
}

/**
 * Check if a given object implements the UserInfoType interface.
 */
export function instanceOfUserInfoType(value: object): value is UserInfoType {
    if (!('externalId' in value) || value['externalId'] === undefined) return false;
    return true;
}

export function UserInfoTypeFromJSON(json: any): UserInfoType {
    return UserInfoTypeFromJSONTyped(json, false);
}

export function UserInfoTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserInfoType {
    if (json == null) {
        return json;
    }
    return {
        
        'externalId': json['externalId'],
    };
}

export function UserInfoTypeToJSON(json: any): UserInfoType {
    return UserInfoTypeToJSONTyped(json, false);
}

export function UserInfoTypeToJSONTyped(value?: UserInfoType | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'externalId': value['externalId'],
    };
}

