### get some sample data
GET http://localhost:5144/Indicators/100/data
    ?areaCodes=areaCode1
    &years=1970
    &years=1980
    &areaCodes=unknownAreaCode
    &areaCodes=areaCode2

###

### attempt to use indicatorId hardcoded to generate exception
GET http://localhost:5144/Indicators/-1/data

###

### attempt to use invalid indicatorId
GET http://localhost:5144/Indicators/sausage/data

###

### attempt to use invalid years
GET http://localhost:5144/Indicators/100/data
    ?years=sausage

###