### get some sample data
# sample indicators: 1, 6, 40, 41, 355
# sample area: E38000058, E38000071, E38000115

GET http://localhost:5144/Indicators/108/data
    ?areaCodes=areaCode1
    &years=1970
    &years=1980
    &areaCodes=unknownAreaCode
    &areaCodes=areaCode2

###

### attempt to use indicatorId hardcoded to generate exception
GET http://localhost:5144/Indicators/-1/data

###

### attempt to use invalid indicatorId
GET http://localhost:5144/Indicators/sausage/data

###

### attempt to use invalid years
GET http://localhost:5144/Indicators/355/data
    ?years=sausage

###

### example with benchmark comparison
GET http://localhost:5144/indicators/247/data?area_codes=N81096&comparison_method=Rag
###

