CREATE TABLE [dbo].[AgeDimension](
	[AgeKey] [smallint] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[AgeID] [smallint] NOT NULL,
 CONSTRAINT [PK_AgeDimesnion] PRIMARY KEY CLUSTERED 
(
	[AgeKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]