CREATE TABLE [dbo].[PeriodDimension](
	[PeriodKey] [tinyint] IDENTITY(1,1) NOT NULL,
	[Period] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_PeriodDimension] PRIMARY KEY CLUSTERED 
(
	[PeriodKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

