/* tslint:disable */
/* eslint-disable */
/**
 * DHSC.FingertipsNext.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  WeatherForecast,
} from '../models/index';
import {
    WeatherForecastFromJSON,
    WeatherForecastToJSON,
} from '../models/index';

export interface CoreForecastGetRequest {
    apiVersion?: string;
    xVersion?: string;
}

export interface CoreSearchForecastGetRequest {
    searchTerm?: string;
    apiVersion?: string;
    xVersion?: string;
}

/**
 * CoreApi - interface
 * 
 * @export
 * @interface CoreApiInterface
 */
export interface CoreApiInterface {
    /**
     * 
     * @param {string} [apiVersion] 
     * @param {string} [xVersion] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CoreApiInterface
     */
    coreForecastGetRaw(requestParameters: CoreForecastGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<WeatherForecast>>>;

    /**
     */
    coreForecastGet(requestParameters: CoreForecastGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<WeatherForecast>>;

    /**
     * 
     * @param {string} [searchTerm] 
     * @param {string} [apiVersion] 
     * @param {string} [xVersion] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CoreApiInterface
     */
    coreSearchForecastGetRaw(requestParameters: CoreSearchForecastGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>>;

    /**
     */
    coreSearchForecastGet(requestParameters: CoreSearchForecastGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string>;

}

/**
 * 
 */
export class CoreApi extends runtime.BaseAPI implements CoreApiInterface {

    /**
     */
    async coreForecastGetRaw(requestParameters: CoreForecastGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<WeatherForecast>>> {
        const queryParameters: any = {};

        if (requestParameters['apiVersion'] != null) {
            queryParameters['api-version'] = requestParameters['apiVersion'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xVersion'] != null) {
            headerParameters['X-Version'] = String(requestParameters['xVersion']);
        }

        const response = await this.request({
            path: `/Core/forecast`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(WeatherForecastFromJSON));
    }

    /**
     */
    async coreForecastGet(requestParameters: CoreForecastGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<WeatherForecast>> {
        const response = await this.coreForecastGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async coreSearchForecastGetRaw(requestParameters: CoreSearchForecastGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const queryParameters: any = {};

        if (requestParameters['searchTerm'] != null) {
            queryParameters['searchTerm'] = requestParameters['searchTerm'];
        }

        if (requestParameters['apiVersion'] != null) {
            queryParameters['api-version'] = requestParameters['apiVersion'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xVersion'] != null) {
            headerParameters['X-Version'] = String(requestParameters['xVersion']);
        }

        const response = await this.request({
            path: `/Core/search-forecast`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async coreSearchForecastGet(requestParameters: CoreSearchForecastGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.coreSearchForecastGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
