/* tslint:disable */
/* eslint-disable */
/**
 * Fingertips API
 * An API to query public health indicator data.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: ProfileFeedback@dhsc.gov.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  FilterIndicators400Response,
  PopulationDataForArea,
} from '../models/index';
import {
    FilterIndicators400ResponseFromJSON,
    FilterIndicators400ResponseToJSON,
    PopulationDataForAreaFromJSON,
    PopulationDataForAreaToJSON,
} from '../models/index';

export interface AreasPopulationDataGetRequest {
    areaCodes?: Array<string>;
    years?: Array<number>;
}

/**
 * AreasApi - interface
 * 
 * @export
 * @interface AreasApiInterface
 */
export interface AreasApiInterface {
    /**
     * Get population data for requested areas
     * @summary Get population data for up to 10 area codes
     * @param {Array<string>} [areaCodes] A list of area codes, up to 10 area codes can be requested
     * @param {Array<number>} [years] A list of years, up to 10 years can be requested
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AreasApiInterface
     */
    areasPopulationDataGetRaw(requestParameters: AreasPopulationDataGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PopulationDataForArea>>>;

    /**
     * Get population data for requested areas
     * Get population data for up to 10 area codes
     */
    areasPopulationDataGet(requestParameters: AreasPopulationDataGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PopulationDataForArea>>;

}

/**
 * 
 */
export class AreasApi extends runtime.BaseAPI implements AreasApiInterface {

    /**
     * Get population data for requested areas
     * Get population data for up to 10 area codes
     */
    async areasPopulationDataGetRaw(requestParameters: AreasPopulationDataGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PopulationDataForArea>>> {
        const queryParameters: any = {};

        if (requestParameters['areaCodes'] != null) {
            queryParameters['area_codes'] = requestParameters['areaCodes'];
        }

        if (requestParameters['years'] != null) {
            queryParameters['years'] = requestParameters['years'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/areas/population/data`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PopulationDataForAreaFromJSON));
    }

    /**
     * Get population data for requested areas
     * Get population data for up to 10 area codes
     */
    async areasPopulationDataGet(requestParameters: AreasPopulationDataGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PopulationDataForArea>> {
        const response = await this.areasPopulationDataGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
