/* tslint:disable */
/* eslint-disable */
/**
 * Fingertips API
 * An API to query public health indicator data.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: ProfileFeedback@dhsc.gov.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AreaWithRelations,
  GetAreaHierarchies500Response,
  PopulationDataForArea,
  RootArea,
} from '../models/index';
import {
    AreaWithRelationsFromJSON,
    AreaWithRelationsToJSON,
    GetAreaHierarchies500ResponseFromJSON,
    GetAreaHierarchies500ResponseToJSON,
    PopulationDataForAreaFromJSON,
    PopulationDataForAreaToJSON,
    RootAreaFromJSON,
    RootAreaToJSON,
} from '../models/index';

export interface AreasPopulationDataGetRequest {
    areaCodes?: Array<string>;
    years?: Array<number>;
}

export interface GetAreaRequest {
    areaCode: string;
    includeChildren?: boolean;
    includeSiblings?: boolean;
    includeCousins?: boolean;
    includeAncestors?: boolean;
}

export interface GetAreaTypesRequest {
    hierarchyType?: string;
}

/**
 * AreasApi - interface
 * 
 * @export
 * @interface AreasApiInterface
 */
export interface AreasApiInterface {
    /**
     * Get population data for requested areas
     * @summary Get population data for up to 10 area codes
     * @param {Array<string>} [areaCodes] A list of area codes, up to 10 area codes can be requested
     * @param {Array<number>} [years] A list of years, up to 10 years can be requested
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AreasApiInterface
     */
    areasPopulationDataGetRaw(requestParameters: AreasPopulationDataGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PopulationDataForArea>>>;

    /**
     * Get population data for requested areas
     * Get population data for up to 10 area codes
     */
    areasPopulationDataGet(requestParameters: AreasPopulationDataGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PopulationDataForArea>>;

    /**
     * Get the full details of a given area, including it\'s parent, optionally including it\'s children, siblings, cousins and ancestors
     * @summary Get area
     * @param {string} areaCode The area code of the area/ geography
     * @param {boolean} [includeChildren] include the child areas
     * @param {boolean} [includeSiblings] include the sibling areas
     * @param {boolean} [includeCousins] include the cousin areas
     * @param {boolean} [includeAncestors] include the ancestor areas
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AreasApiInterface
     */
    getAreaRaw(requestParameters: GetAreaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AreaWithRelations>>;

    /**
     * Get the full details of a given area, including it\'s parent, optionally including it\'s children, siblings, cousins and ancestors
     * Get area
     */
    getArea(requestParameters: GetAreaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AreaWithRelations>;

    /**
     * Get all available hierarchy types
     * @summary Get hierarchies
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AreasApiInterface
     */
    getAreaHierarchiesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>>;

    /**
     * Get all available hierarchy types
     * Get hierarchies
     */
    getAreaHierarchies(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>>;

    /**
     * Get the root node of the area hierarchy
     * @summary Get root
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AreasApiInterface
     */
    getAreaRootRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RootArea>>;

    /**
     * Get the root node of the area hierarchy
     * Get root
     */
    getAreaRoot(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RootArea>;

    /**
     * Get area types, optionally filtering by hierarchy type
     * @summary Get area types
     * @param {string} [hierarchyType] The name of the hierarchy type
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AreasApiInterface
     */
    getAreaTypesRaw(requestParameters: GetAreaTypesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>>;

    /**
     * Get area types, optionally filtering by hierarchy type
     * Get area types
     */
    getAreaTypes(requestParameters: GetAreaTypesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>>;

}

/**
 * 
 */
export class AreasApi extends runtime.BaseAPI implements AreasApiInterface {

    /**
     * Get population data for requested areas
     * Get population data for up to 10 area codes
     */
    async areasPopulationDataGetRaw(requestParameters: AreasPopulationDataGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PopulationDataForArea>>> {
        const queryParameters: any = {};

        if (requestParameters['areaCodes'] != null) {
            queryParameters['area_codes'] = requestParameters['areaCodes'];
        }

        if (requestParameters['years'] != null) {
            queryParameters['years'] = requestParameters['years'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/areas/population/data`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PopulationDataForAreaFromJSON));
    }

    /**
     * Get population data for requested areas
     * Get population data for up to 10 area codes
     */
    async areasPopulationDataGet(requestParameters: AreasPopulationDataGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PopulationDataForArea>> {
        const response = await this.areasPopulationDataGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get the full details of a given area, including it\'s parent, optionally including it\'s children, siblings, cousins and ancestors
     * Get area
     */
    async getAreaRaw(requestParameters: GetAreaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AreaWithRelations>> {
        if (requestParameters['areaCode'] == null) {
            throw new runtime.RequiredError(
                'areaCode',
                'Required parameter "areaCode" was null or undefined when calling getArea().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['includeChildren'] != null) {
            queryParameters['includeChildren'] = requestParameters['includeChildren'];
        }

        if (requestParameters['includeSiblings'] != null) {
            queryParameters['includeSiblings'] = requestParameters['includeSiblings'];
        }

        if (requestParameters['includeCousins'] != null) {
            queryParameters['includeCousins'] = requestParameters['includeCousins'];
        }

        if (requestParameters['includeAncestors'] != null) {
            queryParameters['includeAncestors'] = requestParameters['includeAncestors'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/areas/{area_code}`.replace(`{${"area_code"}}`, encodeURIComponent(String(requestParameters['areaCode']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AreaWithRelationsFromJSON(jsonValue));
    }

    /**
     * Get the full details of a given area, including it\'s parent, optionally including it\'s children, siblings, cousins and ancestors
     * Get area
     */
    async getArea(requestParameters: GetAreaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AreaWithRelations> {
        const response = await this.getAreaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get all available hierarchy types
     * Get hierarchies
     */
    async getAreaHierarchiesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/areas/hierarchies`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get all available hierarchy types
     * Get hierarchies
     */
    async getAreaHierarchies(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>> {
        const response = await this.getAreaHierarchiesRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get the root node of the area hierarchy
     * Get root
     */
    async getAreaRootRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RootArea>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/areas/root`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RootAreaFromJSON(jsonValue));
    }

    /**
     * Get the root node of the area hierarchy
     * Get root
     */
    async getAreaRoot(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RootArea> {
        const response = await this.getAreaRootRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get area types, optionally filtering by hierarchy type
     * Get area types
     */
    async getAreaTypesRaw(requestParameters: GetAreaTypesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>> {
        const queryParameters: any = {};

        if (requestParameters['hierarchyType'] != null) {
            queryParameters['hierarchy_type'] = requestParameters['hierarchyType'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/areas/areatypes`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get area types, optionally filtering by hierarchy type
     * Get area types
     */
    async getAreaTypes(requestParameters: GetAreaTypesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>> {
        const response = await this.getAreaTypesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
