/* tslint:disable */
/* eslint-disable */
/**
 * Fingertips API
 * An API to query public health indicator data.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ProfileFeedback@dhsc.gov.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BadRequest,
  GetAreaHierarchies500Response,
  Indicator,
  IndicatorSummary,
  IndicatorWithHealthDataForArea,
  QuartileData,
} from '../models/index';
import {
    BadRequestFromJSON,
    BadRequestToJSON,
    GetAreaHierarchies500ResponseFromJSON,
    GetAreaHierarchies500ResponseToJSON,
    IndicatorFromJSON,
    IndicatorToJSON,
    IndicatorSummaryFromJSON,
    IndicatorSummaryToJSON,
    IndicatorWithHealthDataForAreaFromJSON,
    IndicatorWithHealthDataForAreaToJSON,
    QuartileDataFromJSON,
    QuartileDataToJSON,
} from '../models/index';

export interface FilterIndicatorsRequest {
    indicatorIds?: Array<number>;
}

export interface GetHealthDataForAnIndicatorRequest {
    indicatorId: number;
    areaCodes?: Array<string>;
    areaType?: string;
    years?: Array<number>;
    inequalities?: Array<GetHealthDataForAnIndicatorInequalitiesEnum>;
}

export interface GetIndicatorRequest {
    indicatorId: number;
}

export interface IndicatorsQuartilesGetRequest {
    areaCode: string;
    ancestorCode: string;
    indicatorIds?: Array<number>;
    areaType?: string;
}

/**
 * IndicatorsApi - interface
 * 
 * @export
 * @interface IndicatorsApiInterface
 */
export interface IndicatorsApiInterface {
    /**
     * Get summaries of public health indicators, by passing in the appropriate options you can filter the results 
     * @summary Get indicator summaries & filter results
     * @param {Array<number>} [indicatorIds] A list of indicator_ids, up to 10 can be requested
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IndicatorsApiInterface
     */
    filterIndicatorsRaw(requestParameters: FilterIndicatorsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<IndicatorSummary>>>;

    /**
     * Get summaries of public health indicators, by passing in the appropriate options you can filter the results 
     * Get indicator summaries & filter results
     */
    filterIndicators(requestParameters: FilterIndicatorsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<IndicatorSummary>>;

    /**
     * Get data for a public health indicator. This will return all data for all areas and all years for the indicators. Optionally filter the results by supplying one or more area codes and one or more years in the query string.
     * @summary Get health data for an indicator
     * @param {number} indicatorId The unique identifier of the indicator
     * @param {Array<string>} [areaCodes] A list of area codes, up to 10 area codes can be requested
     * @param {string} [areaType] The area type which the areas belong to
     * @param {Array<number>} [years] A list of years, up to 10 years can be requested
     * @param {Array<'age' | 'sex' | 'deprivation'>} [inequalities] Determines the kind of inequality data that should be returned if an option is specified
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IndicatorsApiInterface
     */
    getHealthDataForAnIndicatorRaw(requestParameters: GetHealthDataForAnIndicatorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IndicatorWithHealthDataForArea>>;

    /**
     * Get data for a public health indicator. This will return all data for all areas and all years for the indicators. Optionally filter the results by supplying one or more area codes and one or more years in the query string.
     * Get health data for an indicator
     */
    getHealthDataForAnIndicator(requestParameters: GetHealthDataForAnIndicatorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IndicatorWithHealthDataForArea>;

    /**
     * Fetches details of a specific indicator by its unique identifier. The response includes the indicator\'s metadata 
     * @summary Get indicator
     * @param {number} indicatorId The unique identifier of the indicator
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IndicatorsApiInterface
     */
    getIndicatorRaw(requestParameters: GetIndicatorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Indicator>>;

    /**
     * Fetches details of a specific indicator by its unique identifier. The response includes the indicator\'s metadata 
     * Get indicator
     */
    getIndicator(requestParameters: GetIndicatorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Indicator>;

    /**
     * Get quartile information for indicators including  
     * @summary Get quartile values for indicators
     * @param {string} areaCode The area code of the area/ geography
     * @param {string} ancestorCode The area code of an ancestor area
     * @param {Array<number>} [indicatorIds] A list of indicator_ids, up to 10 can be requested
     * @param {string} [areaType] The area type which the areas belong to
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IndicatorsApiInterface
     */
    indicatorsQuartilesGetRaw(requestParameters: IndicatorsQuartilesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<QuartileData>>>;

    /**
     * Get quartile information for indicators including  
     * Get quartile values for indicators
     */
    indicatorsQuartilesGet(requestParameters: IndicatorsQuartilesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<QuartileData>>;

}

/**
 * 
 */
export class IndicatorsApi extends runtime.BaseAPI implements IndicatorsApiInterface {

    /**
     * Get summaries of public health indicators, by passing in the appropriate options you can filter the results 
     * Get indicator summaries & filter results
     */
    async filterIndicatorsRaw(requestParameters: FilterIndicatorsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<IndicatorSummary>>> {
        const queryParameters: any = {};

        if (requestParameters['indicatorIds'] != null) {
            queryParameters['indicator_ids'] = requestParameters['indicatorIds'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/indicators`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(IndicatorSummaryFromJSON));
    }

    /**
     * Get summaries of public health indicators, by passing in the appropriate options you can filter the results 
     * Get indicator summaries & filter results
     */
    async filterIndicators(requestParameters: FilterIndicatorsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<IndicatorSummary>> {
        const response = await this.filterIndicatorsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get data for a public health indicator. This will return all data for all areas and all years for the indicators. Optionally filter the results by supplying one or more area codes and one or more years in the query string.
     * Get health data for an indicator
     */
    async getHealthDataForAnIndicatorRaw(requestParameters: GetHealthDataForAnIndicatorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IndicatorWithHealthDataForArea>> {
        if (requestParameters['indicatorId'] == null) {
            throw new runtime.RequiredError(
                'indicatorId',
                'Required parameter "indicatorId" was null or undefined when calling getHealthDataForAnIndicator().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['areaCodes'] != null) {
            queryParameters['area_codes'] = requestParameters['areaCodes'];
        }

        if (requestParameters['areaType'] != null) {
            queryParameters['area_type'] = requestParameters['areaType'];
        }

        if (requestParameters['years'] != null) {
            queryParameters['years'] = requestParameters['years'];
        }

        if (requestParameters['inequalities'] != null) {
            queryParameters['inequalities'] = requestParameters['inequalities'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/indicators/{indicator_id}/data`.replace(`{${"indicator_id"}}`, encodeURIComponent(String(requestParameters['indicatorId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IndicatorWithHealthDataForAreaFromJSON(jsonValue));
    }

    /**
     * Get data for a public health indicator. This will return all data for all areas and all years for the indicators. Optionally filter the results by supplying one or more area codes and one or more years in the query string.
     * Get health data for an indicator
     */
    async getHealthDataForAnIndicator(requestParameters: GetHealthDataForAnIndicatorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IndicatorWithHealthDataForArea> {
        const response = await this.getHealthDataForAnIndicatorRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Fetches details of a specific indicator by its unique identifier. The response includes the indicator\'s metadata 
     * Get indicator
     */
    async getIndicatorRaw(requestParameters: GetIndicatorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Indicator>> {
        if (requestParameters['indicatorId'] == null) {
            throw new runtime.RequiredError(
                'indicatorId',
                'Required parameter "indicatorId" was null or undefined when calling getIndicator().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/indicators/{indicator_id}`.replace(`{${"indicator_id"}}`, encodeURIComponent(String(requestParameters['indicatorId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IndicatorFromJSON(jsonValue));
    }

    /**
     * Fetches details of a specific indicator by its unique identifier. The response includes the indicator\'s metadata 
     * Get indicator
     */
    async getIndicator(requestParameters: GetIndicatorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Indicator> {
        const response = await this.getIndicatorRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get quartile information for indicators including  
     * Get quartile values for indicators
     */
    async indicatorsQuartilesGetRaw(requestParameters: IndicatorsQuartilesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<QuartileData>>> {
        if (requestParameters['areaCode'] == null) {
            throw new runtime.RequiredError(
                'areaCode',
                'Required parameter "areaCode" was null or undefined when calling indicatorsQuartilesGet().'
            );
        }

        if (requestParameters['ancestorCode'] == null) {
            throw new runtime.RequiredError(
                'ancestorCode',
                'Required parameter "ancestorCode" was null or undefined when calling indicatorsQuartilesGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['indicatorIds'] != null) {
            queryParameters['indicator_ids'] = requestParameters['indicatorIds'];
        }

        if (requestParameters['areaType'] != null) {
            queryParameters['area_type'] = requestParameters['areaType'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/indicators/quartiles`.replace(`{${"area_code"}}`, encodeURIComponent(String(requestParameters['areaCode']))).replace(`{${"ancestor_code"}}`, encodeURIComponent(String(requestParameters['ancestorCode']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(QuartileDataFromJSON));
    }

    /**
     * Get quartile information for indicators including  
     * Get quartile values for indicators
     */
    async indicatorsQuartilesGet(requestParameters: IndicatorsQuartilesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<QuartileData>> {
        const response = await this.indicatorsQuartilesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetHealthDataForAnIndicatorInequalitiesEnum = {
    Age: 'age',
    Sex: 'sex',
    Deprivation: 'deprivation'
} as const;
export type GetHealthDataForAnIndicatorInequalitiesEnum = typeof GetHealthDataForAnIndicatorInequalitiesEnum[keyof typeof GetHealthDataForAnIndicatorInequalitiesEnum];
