/* tslint:disable */
/* eslint-disable */
/**
 * Fingertips API
 * An API to query public health indicator data.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ProfileFeedback@dhsc.gov.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetHealthcheck200Response,
  GetHealthcheck500Response,
} from '../models/index';
import {
    GetHealthcheck200ResponseFromJSON,
    GetHealthcheck200ResponseToJSON,
    GetHealthcheck500ResponseFromJSON,
    GetHealthcheck500ResponseToJSON,
} from '../models/index';

/**
 * SystemApi - interface
 * 
 * @export
 * @interface SystemApiInterface
 */
export interface SystemApiInterface {
    /**
     * Returns the health status of the API.
     * @summary API Health Check
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SystemApiInterface
     */
    getHealthcheckRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetHealthcheck200Response>>;

    /**
     * Returns the health status of the API.
     * API Health Check
     */
    getHealthcheck(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetHealthcheck200Response>;

}

/**
 * 
 */
export class SystemApi extends runtime.BaseAPI implements SystemApiInterface {

    /**
     * Returns the health status of the API.
     * API Health Check
     */
    async getHealthcheckRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetHealthcheck200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/healthcheck`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetHealthcheck200ResponseFromJSON(jsonValue));
    }

    /**
     * Returns the health status of the API.
     * API Health Check
     */
    async getHealthcheck(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetHealthcheck200Response> {
        const response = await this.getHealthcheckRaw(initOverrides);
        return await response.value();
    }

}
