export enum EnvironmentVariables {
    INDICATOR_SEARCH_INDEX_NAME = 'INDICATOR_SEARCH_INDEX_NAME',
    AREA_SEARCH_INDEX_NAME = 'AREA_SEARCH_INDEX_NAME',

    FINGERTIPS_API_URL= 'FINGERTIPS_API_URL',
    DHSC_AI_SEARCH_SERVICE_URL = 'DHSC_AI_SEARCH_SERVICE_URL',
    DHSC_AI_SEARCH_API_KEY = 'DHSC_AI_SEARCH_API_KEY',
    NEXT_RUNTIME = 'NEXT_RUNTIME', // e.g. nodejs
    MOCK_SERVER = 'MOCK_SERVER', // e.g. true
    APPLICATIONINSIGHTS_CONNECTION_STRING = 'APPLICATIONINSIGHTS_CONNECTION_STRING',
    CI = 'CI', // playwright,
    JOB_URL = 'JOB_URL', // platwright
    FINGERTIPS_FRONTEND_URL = 'FINGERTIPS_FRONTEND_URL', // playwright
};

export default EnvironmentVariables;
