area_codes:
  in: query
  name: area_codes
  description: A list of area codes, up to 300 area codes can be requested
  style: form
  schema:
    type: array
    items:
      type: string
      example: G82109
    maxItems: 300
