openapi: 3.0.0
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://fingertips-next-api/1.0.0
info:
  description: An API to query public health indicator data.
  version: "1.0.0"
  title: Fingertips API
  contact:
    email:  ProfileFeedback@dhsc.gov.uk
tags:
  - name: indicators
    description: Endpoints dealing with public health indicators
  - name: areas
    description: Endpoints dealing with areas / geography
paths:
  /area/hierarchies:
    get:
      tags:
        - areas
      summary: Get hierarchies
      description: Get all available hierarchy types
      operationId: getAreaHierarchies
      responses:
        '200':
          description: The available hierarchy types, e.g. NHS or Administrative
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        '500':
          $ref: "#/components/responses/InternalServerErrror"
  /area/areatypes:
    get:
      tags:
        - areas
      summary: Get area types
      description: Get area types, optionally filtering by hierarchy type
      operationId: getAreaTypes
      parameters:
        - $ref: "#/components/parameters/hierarchy_type"
      responses:
        '200':
          description: The available area types e.g. CCB, PCN or GP Surgery
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        '500':
          $ref: "#/components/responses/InternalServerErrror"
  /area/{area_code}:
    get:
      tags:
        - areas
      summary: Get area
      description: Get the full details of a given area, including it's parent, optionally including it's children, siblings, cousins and ancestors
      operationId: getArea
      parameters:
        - $ref: "#/components/parameters/area_code"
        - $ref: "#/components/parameters/includeChildren"
        - $ref: "#/components/parameters/includeSiblings"
        - $ref: "#/components/parameters/includeCousins"
        - $ref: "#/components/parameters/includeAncestors"
      responses:
        '200':
          description: The area node
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AreaWithRelations'
        '400':
          $ref: "#/components/responses/BadRequest"
        '500':
          $ref: "#/components/responses/InternalServerErrror"
  /area/root:
    get:
      tags:
        - areas
      summary: Get root
      description: Get the root node of the area hierarchy
      operationId: getAreaRoot
      responses:
        '200':
          description: The root area node
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RootArea'
        '500':
          $ref: "#/components/responses/InternalServerErrror"
  /area/{area_code}/children:
    get:
      tags:
        - areas
      summary: Get child
      description: Get child nodes for a given area
      operationId: getAreaChildren
      parameters:
        - $ref: "#/components/parameters/area_code"
      responses:
        '200':
          description: The child nodes for the area
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Area'
        '400':
          $ref: "#/components/responses/BadRequest"
        '500':
          $ref: "#/components/responses/InternalServerErrror"
  /area/{area_code}/ancestors:
    get:
      tags:
        - areas
      summary: Get ancestors
      description: Get ancestor nodes (parent, grandparent etc.) for a given area
      operationId: getAreaAncestors
      parameters:
        - $ref: "#/components/parameters/area_code"
      responses:
        '200':
          description: The ancestor nodes for the area
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Area'
        '400':
          $ref: "#/components/responses/BadRequest"
        '500':
          $ref: "#/components/responses/InternalServerErrror"
  /area/{area_code}/siblings:
    get:
      tags:
        - areas
      summary: Get siblings
      description: Get sibling nodes (nodes with the same parent) for a given area
      operationId: getAreaSiblings
      parameters:
        - $ref: "#/components/parameters/area_code"
      responses:
        '200':
          description: The sibling nodes for the area, includes the area itself
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Area'
        '400':
          $ref: "#/components/responses/BadRequest"
        '500':
          $ref: "#/components/responses/InternalServerErrror"
  /geography/{area_code}/siblingscousins:
    get:
      tags:
        - geography
      summary: Get siblings
      description: Get nodes at the same level as the given geography, in the same hierarchy type. This includes siblings and cousins
      operationId: getGeographySiblingsAndCousins
      parameters:
        - $ref: "#/components/parameters/area_code"
      responses:
        '200':
          description: The sibling and cousin nodes for the geography, includes the geography itself
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Area'
        '400':
          $ref: "#/components/responses/BadRequest"
        '500':
          $ref: "#/components/responses/InternalServerErrror"
  /indicators:
    get:
      tags:
        - indicators
      summary: Get indicator summaries & filter results
      operationId: filterIndicators
      description: |
        Get summaries of public health indicators, by passing in the appropriate options you can filter the results
      parameters:
        - $ref: "#/components/parameters/indicator_ids"
      responses:
        '200':
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/IndicatorSummary'
        '400':
          $ref: "#/components/responses/BadRequest"
        '500':
          $ref: "#/components/responses/InternalServerErrror"
  /indicators/{indicator_id}:
    get:
      tags:
        - indicators
      summary: Get indicator
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Indicator"
          description: The request was successful, and the server has returned the
            requested resource in the response body.
        '404':
          $ref: "#/components/responses/NotFound"
        '500':
           $ref: "#/components/responses/InternalServerErrror"
      parameters:
        - $ref: "#/components/parameters/indicator_id"
      description: >
        Fetches details of a specific indicator by its unique identifier. The
        response includes the indicator's metadata
      operationId: getIndicator
  /indicators/{indicator_id}/data:
    get:
      tags:
        - indicators
      summary: Get health data for an indicator
      description: Get data for a public health indicator. This will return all data for all areas and all years for the indicators. Optionally filter the results by supplying one
        or more area codes and one or more years in the query string.
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/HealthDataForArea"
                title: GetHealthDataForAnIndicatorOk
          description: Data containing the health data points for the indicator, years
            and geographical areas requested
        "400":
          $ref: "#/components/responses/BadRequest"
        "500":
          $ref: "#/components/responses/InternalServerErrror"
      parameters:
        - $ref: "#/components/parameters/indicator_id"
        - $ref: "#/components/parameters/area_codes"
        - $ref: "#/components/parameters/years"
      operationId: getHealthDataForAnIndicator
components:
  schemas:
    RootArea:
      type: object
      description: The root node of the area / geography hierarchies
      required:
        - code
        - name
      properties:
        code:
          type: string
          example: "E92000001"
          description: The unique area code of the area / geography
        name:
          type: string
          example: "England"
          description: The name of the area / geography
    Area:
      type: object
      description: A area or geography that has associated public health data
      required:
        - code
        - name
        - hierarchyType
        - areaType
      properties:
        code:
          type: string
          example: "E06000047"
          description: The unique area code of the area / geography
        name:
          type: string
          example: "County Durham"
          description: The name of the area / geography
        hierarchyType:
          type: string
          example: "NHS"
          description: The name of the associated hierarchy for the area / geography
        areaType:
          type: string
          example: "PCN"
          description: The type of the area / geography
    AreaWithRelations:
      allOf:
        - $ref: "#/components/schemas/Area"
        - type: object
          properties:
            parent:
              $ref: "#/components/schemas/Area"
            children:
              type: array
              items:
                $ref: "#/components/schemas/Area"
            siblings:
              type: array
              items:
                $ref: "#/components/schemas/Area"
            cousins:
              type: array
              items:
                $ref: "#/components/schemas/Area"
            ancestors:
              type: array
              items:
                $ref: "#/components/schemas/Area"
    IndicatorSummary:
      type: object
      description: A summary of a public health indicator
      required:
        - indicator_id
        - title
      properties:
        indicator_id:
          type: integer
          format: int32
          example: 3456
          description: The unique identifier of the indicator
        title:
          type: string
          example: "Hypertension: QOF prevalence (all ages)"
          description: The title of the indicator
    Indicator:
      type: object
      description: A public health indicator
      required:
        - indicator_id
        - title
        - definition
      properties:
        indicator_id:
          type: integer
          format: int32
          example: 3456
          description: The unique identifier of the indicator
        title:
          type: string
          example: "Hypertension: QOF prevalence (all ages)"
          description: The title of the indicator
        definition:
          type: string
          example: "The percentage of patients with established hypertension, as
              recorded on practice disease registers (proportion of total list
              size)"
          description: The definition of the indicator
    HealthDataPoint:
      type: object
      description: Represents a health data point for a public health indicator with a
        count, value, upper confidence interval, lower confidence interval and a
        year.
      required:
        - year
        - count
        - value
        - lowerCi
        - upperCi
      properties:
        year:
          type: integer
          format: int32
          example: 2023
          description: The year that the data point is for
        count:
          type: number
          example: 222
          description: The count
        value:
          type: number
          example: 506.60912
          description: The value
        lowerCi:
          type: number
          example: 441.69151
          description: The lower confidence interval
        upperCi:
          type: number
          format: float
          example: 578.32766
          description: The upper confidence interval
    HealthDataForArea:
      type: object
      description: Associates a list of health data points with the relevant
        geographical area (represented by it's unique code).
      required:
        - areaCode
        - healthData
      properties:
        areaCode:
          type: string
          example: A1426
          description: The unique area code that the health data for
        healthData:
          type: array
          items:
            $ref: "#/components/schemas/HealthDataPoint"
          description: The health data points for the area and indicator
  parameters:
    years:
      in: query
      name: years
      description: A list of years, up to 10 years can be requested
      style: form
      schema:
        type: array
        items:
          type: integer
          example: 2023
        maxItems: 10
    area_code:
      in: path
      name: area_code
      style: simple
      schema:
        type: string
        example: G82109
      explode: false
      required: true
      description: The area code of the area/ geography
    includeChildren:
      in: query
      name: includeChildren
      description: include the child areas
      schema:
        type: boolean
    includeSiblings:
      in: query
      name: includeSiblings
      description: include the sibling areas
      schema:
        type: boolean
    includeCousins:
      in: query
      name: includeCousins
      description: include the cousin areas
      schema:
        type: boolean
    includeAncestors:
      in: query
      name: includeAncestors
      description: include the ancestor areas
      schema:
        type: boolean
    area_codes:
      in: query
      name: area_codes
      description: A list of area codes, up to 10 area codes can be requested
      style: form
      schema:
        type: array
        items:
          type: string
          example: G82109
        maxItems: 10
    indicator_id:
      in: path
      name: indicator_id
      style: simple
      schema:
        type: integer
        example: 1234
        minimum: 1
      explode: false
      required: true
      description: The unique identifier of the indicator
    indicator_ids:
      in: query
      name: indicator_ids
      description: A list of indicator_ids, up to 10 can be requested
      style: form
      schema:
        type: array
        items:
          type: integer
          example: 1234
        maxItems: 10
    hierarchy_type:
      in: query
      name: hierarchy_type
      style: form
      schema:
        type: string
        example: NHS
      description: The name of the hierarchy type
  responses:
    NotFound:
      content:
        application/json:
          schema:
            type: object
            required:
              - message
            properties:
              message:
                type: string
      description: The server cannot find the requested resource. The endpoint may be
        invalid or the resource may no longer exist.
    BadRequest:
      content:
        application/json:
          schema:
            type: object
            required:
              - message
            properties:
              message:
                type: string
      description: The server could not understand the request due to invalid syntax.
        The client should modify the request and try again.
    InternalServerErrror:
      content:
        application/json:
          schema:
            type: object
            required:
              - message
            properties:
              message:
                type: string
      description: The server encountered an unexpected condition that prevented it
        from fulfilling the request. Report the issue to the support team if it
        persists.