openapi: 3.0.0
servers:
  # Added by API Auto Mocking Plugin
  - url: https://fingertips-next-api/1.0.0
    description: SwaggerHub API Auto Mocking
  - url: http://localhost:5144
    description: localhost
info:
  description: An API to query public health indicator data.
  version: "1.0.0"
  title: Fingertips API
  contact:
    email: ProfileFeedback@dhsc.gov.uk
tags:
  - name: indicators
    description: Endpoints dealing with public health indicators
  - name: areas
    description: Endpoints dealing with areas / geography
  - name: system
    description: System endpoints
paths:
  /areas/hierarchies:
    $ref: "./areas/paths.yaml#/hierarchies"
  /areas/areatypes:
    $ref: "./areas/paths.yaml#/areatypes"
  /areas/areatypes/{area_type_key}/areas:
    $ref: "./areas/paths.yaml#/areas_by_area_type"
  /areas/{area_code}:
    $ref: "./areas/paths.yaml#/area_by_area_code"
  /areas/root:
    $ref: "./areas/paths.yaml#/root"
  /areas:
    $ref: "./areas/paths.yaml#/areas"
  /healthcheck:
    $ref: "./system/healthcheck.yaml"
  /indicators:
    $ref: "./indicators/paths.yaml#/indicators"
  /indicators/{indicator_id}:
    $ref: "./indicators/paths.yaml#/indicators_by_indicator_id"
  /indicators/{indicator_id}/data:
    $ref: "./indicators/paths.yaml#/indicators_by_indicator_id_data"
  /indicators/quartiles:
    $ref: "./indicators/paths.yaml#/quartiles"
