batch_id:
  in: path
  name: batch_id
  style: simple
  schema:
    type: string
    example: "12345_2025-01-01T00:00:00.000"
  explode: false
  required: true
  description: The unique identifier of the batch of data