name: Build and Push Container

on:
  workflow_call:
    inputs:
      context-location:
        description: 'The location of the Docker build context'
        required: true
        type: string
      container-tag:
        description: 'The tag for the Docker container'
        required: true
        type: string
      git-semver:
        description: 'Semantic version of the build'
        required: true
        type: string
      git-full-semver:
        description: 'Full semantic version of the build'
        required: true
        type: string
    secrets:
      acr-username:
        description: 'Azure Container Registry username'
        required: true
      acr-password:
        description: 'Azure Container Registry password'
        required: true
      acr-server:
        description: 'Azure Container Registry server'
        required: true

jobs:
  build-and-push:
    name: Build and Push Container
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Azure Container Registry Login
        uses: Azure/docker-login@v1
        with:
          username: ${{ secrets.acr-username }}
          password: ${{ secrets.acr-password }}
          login-server: ${{ secrets.acr-server }}

      - name: Generate container metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.acr-server }}/${{ inputs.container-tag }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            # set latest tag for default branch
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=${{ inputs.git-semver }}
            type=raw,value

      - name: Save Semver Tag
        run: echo "${{ inputs.git-semver }}" > semver-tag.txt
    
      - name: Upload Semver Artifact
        uses: actions/upload-artifact@v4
        with:
          name: semver-tag
          path: semver-tag.txt

      - name: Build and push container
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context-location }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      