name: Build and Push Container

on:
  workflow_call:
    inputs:
      context-location:
        description: 'The location of the Docker build context'
        required: true
        type: string
      container-tag:
        description: 'The tag for the Docker container'
        required: true
        type: string
      git-semver:
        description: 'Semantic version of the build'
        required: true
        type: string
    secrets:
      azure-credentials:
        description: 'Azure Login Credentials'
        required: true
      acr-server:
        description: 'Azure Container Registry server'
        required: true


jobs:
  build-and-push:
    name: Build and Push Container
    runs-on: self-hosted
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - uses: Azure/login@v1
        with:
          creds: ${{ secrets.azure-credentials }}

      - name: Generate container metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.acr-server }}/${{ inputs.container-tag }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            # set latest tag for default branch
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=${{ inputs.git-semver }}

      - name: Build and push container
        run: |
          TAGS=$(echo "${{ steps.meta.outputs.tags }}" | sed -e 's|^[^/]*/||' -e 's/^/-t /' | tr '\n' ' ')
          echo "Formatted tags: ${TAGS}"
          az acr build \
            --registry "${{ secrets.acr-server }}" \
            $TAGS \
            "${{ inputs.context-location }}"
