name: Fingertips CI

env:
  dotnet-version: 9.0.x

on:
  push:
    branches:
      ## ** is required to match branches with / in their name
      - "**"
  pull_request:
    branches:
      - main

jobs:
  git-version:
    name: Determine semantic version number
    runs-on: ubuntu-latest

    outputs:
      sem-ver: ${{ steps.version_step.outputs.semVer }}
      full-sem-ver: ${{ steps.version_step.outputs.fullSemVer }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          # GitVersion requires the entire history
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.0.0
        with:
          versionSpec: "6.x"

      - name: Generate semantic version
        id: version_step
        uses: gittools/actions/gitversion/execute@v3.0.0

  frontend-build:
    name: Build frontend
    runs-on: ubuntu-latest

    env:
      frontend-directory: ./frontend/fingertips-frontend

      # Disable Next.js telemetry tracking (https://nextjs.org/telemetry)
      NEXT_TELEMETRY_DISABLED: true

    strategy:
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version: ["22.x"]

    defaults:
      run:
        working-directory: ${{ env.frontend-directory }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: ${{ env.frontend-directory }}/package-lock.json

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      # - name: Perform type checking
      #   run: npm run typecheck

      - name: Lint code
        run: npm run lint

      - name: run e2e cypress tests
        uses: cypress-io/github-action@v6
        with: 
          working-directory: ${{ env.frontend-directory }}
      - run: npm run test-e2e-ci

  container-build:
    name: Build container
    runs-on: ubuntu-latest
    needs: git-version

    strategy:
      matrix:
        application: ["Frontend", "API"]
        include:
          - application: Frontend
            container-tag: dhsc.fingertipsnext.frontend
            context-location: frontend/fingertips-frontend
          - application: API
            container-tag: dhsc.fingertipsnext.api
            context-location: api/DHSC.FingertipsNext.Api/DHSC.FingertipsNext.Api

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # TODO: Re-enable this when we have Azure access
      # TODO: Investigate the use of OpenID Connect for authentication: https://docs.github.com/en/actions/security-for-github-actions/security-hardening-your-deployments/about-security-hardening-with-openid-connect
      # - name: Login to container registry
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ${{ vars.CONTAINER_REGISTRY }}
      #     username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
      #     password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}

      - name: Generate container metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          # TODO: Tag with the registry name when we have Azure access
          # images: ${{ vars.CONTAINER_REGISTRY }}/${{ matrix.container-tag }}
          images: ${{ matrix.container-tag }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            # set latest tag for default branch
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=${{ needs.git-version.outputs.sem-ver }}
            type=raw,value=${{ needs.git-version.outputs.full-sem-ver }}

      - name: Build and push container
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context-location }}
          # TODO: Re-enable pushing the image to the repository when we have Azure access
          # push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  terraform-build:
    name: Validate Terraform
    runs-on: ubuntu-latest

    strategy:
      matrix:
        tf-dir: ["account", "environment"]

    defaults:
      run:
        working-directory: terraform/${{ matrix.tf-dir }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      - name: Initialise Terraform
        run: terraform init -backend=false

      - name: Validate Terraform configuration
        run: terraform validate

      - name: Check Terraform formatting
        run: terraform fmt -recursive -check -diff

  database-build:
    name: Build database project
    runs-on: ubuntu-latest

    env:
      database-directory: database/fingertips-db

    defaults:
      run:
        working-directory: ${{ env.database-directory }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.dotnet-version }}

      - name: Build database project
        run: dotnet build fingertips-db.sqlproj

      - name: Upload .dacpac file artifact
        uses: actions/upload-artifact@v4
        with:
          name: dacpac
          path: ${{ env.database-directory }}/bin/**/fingertips-db.dacpac
          if-no-files-found: error
