name: Execute e2e tests

env:
  frontend-directory: ./frontend/fingertips-frontend
  NEXT_TELEMETRY_DISABLED: true
  NODE_VERSION: 22.x

on:
  workflow_call:
    inputs:
      env-url:
        description: "environment url to run e2e tests against"
        required: false
        default: null
        type: string

jobs:
  execute-e2e-tests:
    name: Execute e2e tests
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.49.1-jammy

    defaults:
      run:
        working-directory: ${{ env.frontend-directory }}

    steps:
      - uses: actions/checkout@v4
        if: ${{ inputs.env-url == null }}

      - name: Use Node.js ${{ env.NODE_VERSION }}
        if: ${{ inputs.env-url == null }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: ${{ env.frontend-directory }}/package-lock.json

      - name: Install dependencies
        if: ${{ inputs.env-url == null }}
        run: npm ci

      - name: Run Playwright tests
        run: npx playwright test
        env:
          FINGERTIPS_FRONTEND_URL: ${{ inputs.env-url }}

      - uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
