name: Execute e2e tests

env:
  frontend-directory: ./frontend/fingertips-frontend
  NEXT_TELEMETRY_DISABLED: true
  NODE_VERSION: 22.x

on:
  workflow_call:
    inputs:
      env-url:
        description: "environment url to run e2e tests against"
        required: false
        default: null
        type: string
      send-slack-on-fail:
        description: "optionally send a slack message on test failure"
        required: false
        default: "false"
        type: string

jobs:
  execute-e2e-tests:
    name: Execute e2e tests
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.50.0-jammy

    defaults:
      run:
        working-directory: ${{ env.frontend-directory }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: ${{ env.frontend-directory }}/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run Playwright tests
        run: npx playwright test
        env:
          FINGERTIPS_FRONTEND_URL: ${{ inputs.env-url }}

      - name: Upload playwright report and screenshot if e2e tests fail
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: playwright failure artefacts
          path: |
            ${{ env.frontend-directory }}/playwright-report/
            ${{ env.frontend-directory }}/test-results/*/*.png
          retention-days: 10

      - name: Send slack message if e2e tests fail
        if: ${{ failure() && inputs.send-slack-on-fail  == 'true' }}
        run: npx slack-ctrf results ${{ env.frontend-directory }}/ctrf/ctrf-report.json --title "E2E Test Failure - Deployed Fingertips Instance"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
