name: Fingertips API Build

env:
  frontend-directory: ./api
  NEXT_TELEMETRY_DISABLED: true

on:
  workflow_dispatch:
  push:
    branches:
      ## ** is required to match branches with / in their name
      - "**"
    paths:
      - api/**
  pull_request:
    branches:
      - main
    paths:
      - api/**

jobs:
  determine-version:
    uses: ./.github/workflows/determine-semver.yml
    with:
      fetch-depth: 0
      gitversion-version: '6.0.x'

  api-build:
    name: Build API
    runs-on: ubuntu-latest

    env:
      api-directory: ./api
    strategy:
      matrix:
        dotnet-version: ["9.0.x"]

    defaults:
      run:
        working-directory: ${{ env.api-directory }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Restore Packages
        run: dotnet restore

      - name: Build API
        run: dotnet build

      - name: Run Unit Tests
        run: dotnet test

  build-container:
    uses: ./.github/workflows/build-container.yml
    needs: [
      determine-version,
      api-build
    ]
    with:
      context-location: api
      container-tag: dhsc.fingertipsnext.api
      git-semver: ${{ needs.determine-version.outputs.sem-ver }}
      git-full-semver: ${{ needs.determine-version.outputs.full-sem-ver }}
    secrets:
      acr-username: ${{ secrets.AZURE_CONTAINERREGISTRY_USERNAME }}
      acr-password: ${{ secrets.AZURE_CONTAINERREGISTRY_PASSWORD }}
      acr-server: ${{ secrets.AZURE_CONTAINERREGISTRY_SERVER }}

