name: Fingertips Frontend Deploy

on:
  pull_request:
    branches:
      - main
    paths:
      - frontend/fingertips-frontend/**
  push:
    branches:
      - main
    paths:
      - frontend/fingertips-frontend/**
  workflow_dispatch:

jobs:
  frontend-deploy:
    runs-on: ubuntu-latest
    name: 'Frontend Deploy'
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Azure Container Registry Login
        uses: Azure/docker-login@v1
        with:
          username: ${{ secrets.AZURE_CONTAINERREGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_CONTAINERREGISTRY_PASSWORD }}
          login-server: ${{ secrets.AZURE_CONTAINERREGISTRY_SERVER }}

      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          imageToDeploy: "${{ secrets.AZURE_CONTAINERREGISTRY_SERVER }}/dhsc.fingertipsnext.frontend:latest"
          containerAppName: ca-fingertips-frontend-dev-uks-001
          resourceGroup: rg-fingertips-dev-uks-001
          containerAppEnvironment: cae-fingertips-dev-uks-002
          azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}