name: Fingertips Frontend Deploy

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Fingertips Frontend Build]
    types:
      - completed
    branches:
      - main

jobs:
  determine-version:
    uses: ./.github/workflows/determine-semver.yml
    with:
      fetch-depth: 0
      gitversion-version: "6.0.x"

  frontend-deploy-development:
    needs: determine-version
    uses: ./.github/workflows/deploy-container.yml
    with:
      tf_state_file_name: fingertips.frontend.tfstate
      environment: development
      tf_environment: dev
      source_branch: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.head_branch || github.ref_name }}
      source_trigger: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.event || github.event_name }}
      container_image_tag: "dhsc.fingertipsnext.frontend:latest"
      container_name: "fingertips-frontend"
      revision_suffix: ${{ github.run_number }}
      container_port: 3000
      environment_variables: |
        [
          {
            name        = "FINGERTIPS_API_URL"
            secret_name = null
            value       = "${{ vars.DEVELOPMENT_FINGERTIPS_API_URL }}"
          },
          {
            name        = "DHSC_AI_SEARCH_USE_MOCK_SERVICE"
            secret_name = null
            value       = false
          },
          {
            name        = "DHSC_AI_SEARCH_API_KEY"
            secret_name = "fingertips-ai-search-api-key"
            value       = null
          },
          {
            name        = "DHSC_AI_SEARCH_SERVICE_URL"
            secret_name = "fingertips-ai-search-url"
            value       = null
          },
          {
            name        = "APPLICATIONINSIGHTS_CONNECTION_STRING"
            secret_name = "fingertips-frontend-application-insights"
            value       = null
          }
        ]
      container_liveness_probe: |
        {
          path      = "/"
          port      = 3000
          transport = "HTTP"
        }
    secrets:
      arm-client-id: ${{ secrets.ARM_CLIENT_ID }}
      arm-client-secret: ${{ secrets.ARM_CLIENT_SECRET }}
      arm-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      arm-tenant-id: ${{ secrets.AZURE_TENANT_ID }}

  e2e-tests-development:
    uses: ./.github/workflows/e2e-tests.yml
    if: |
      ${{
        github.event_name == 'workflow_dispatch' ||
        (
          github.event_name == 'workflow_run' &&
          (
            github.event.workflow_run.event == 'push' ||
            github.event.workflow_run.event == 'workflow_dispatch'
          )
        )
      }}
    needs: frontend-deploy-development
    with:
      env-url: ${{ needs.frontend-deploy-development.outputs.frontend-dev-url }}
      send-slack-on-fail: "true"
    secrets:
      slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}