name: Fingertips DB Deploy

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Fingertips DB Build]
    types:
      - completed
    branches:
      - main

jobs:
  deploy-db-dacpac:
    runs-on: windows-latest
    strategy:
      matrix:
        environment: [
          development
        ]
    environment: ${{ matrix.environment }}

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.head_branch || github.ref_name }}

    - name: Set and use run_id dynamically
      shell: pwsh
      run: |
        if ("${{ github.event_name }}" -eq "workflow_run") {
          $RUN_ID = "${{ github.event.workflow_run.id }}"
          Write-Output "Using workflow run"
        } else {
          Write-Output "Using other triggers"

          # Fetch latest workflow run ID
          $response = Invoke-RestMethod -Uri "https://api.github.com/repos/${{ github.repository }}/actions/workflows/fingertips-db-build.yml/runs?branch=main&status=completed&per_page=1" `
            -Headers @{ "Authorization" = "Bearer ${{ secrets.GITHUB_TOKEN }}"; "Accept" = "application/vnd.github.v3+json" }

          $RUN_ID = $response.workflow_runs[0].id
        }

        Write-Output "Looking for $RUN_ID"
        echo "RUN_ID=$RUN_ID" | Out-File -FilePath $env:GITHUB_ENV -Append
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Download DACPAC
      uses: actions/download-artifact@v4
      with:
        name: dacpac
        run-id: ${{ env.RUN_ID }}
        github-token: ${{ github.token }}

    - uses: azure/sql-action@v2.3
      with:
        connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
        path: 'fingertips-db.dacpac'
        action: 'publish'
        arguments: '/p:DropObjectsNotInSource=true /p:BlockOnPossibleDataLoss=false'