name: Fingertips Frontend Deploy

env:
  frontend-directory: ./frontend/fingertips-frontend
  url: http://4.158.39.145/search

on:
  workflow_run:
    workflows: [Fingertips Frontend Build]
    types:
      - completed
    branches:
      - main

jobs:
  determine-version:
    uses: ./.github/workflows/determine-semver.yml
    with:
      fetch-depth: 0
      gitversion-version: "6.0.x"

  frontend-deploy:
    runs-on: ubuntu-latest
    needs: determine-version
    strategy:
      matrix:
        environment:
          - development
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: "Frontend Deploy"
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Azure Container Registry Login
        uses: Azure/docker-login@v1
        with:
          username: ${{ secrets.AZURE_CONTAINERREGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_CONTAINERREGISTRY_PASSWORD }}
          login-server: ${{ secrets.AZURE_CONTAINERREGISTRY_SERVER }}

      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          imageToDeploy: "${{ secrets.AZURE_CONTAINERREGISTRY_SERVER }}/dhsc.fingertipsnext.frontend:${{ needs.determine-version.outputs.sem-ver }}"
          containerAppName: fingertips-frontend
          resourceGroup: ${{ vars.RESOURCE_GROUP }}
          containerAppEnvironment: ${{ vars.CONTAINER_APP_ENVIRONMENT }}
          registryUrl: ${{ secrets.AZURE_CONTAINERREGISTRY_SERVER }}
          registryUsername: ${{ secrets.AZURE_CONTAINERREGISTRY_USERNAME }}
          registryPassword: ${{ secrets.AZURE_CONTAINERREGISTRY_PASSWORD }}
          targetPort: 3000
          environmentVariables: "FINGERTIPS_API_URL=${{ vars.FINGERTIPS_API_URL }}"
          azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}
        env:
          AZURE_CONFIG_DIR: $HOME/.azure

  e2e-tests:
    name: Execute e2e tests
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.49.1-jammy

    strategy:
      matrix:
        node-version: ["22.x"]

    defaults:
      run:
        working-directory: ${{ env.frontend-directory }}

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: ${{ env.frontend-directory }}/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run Playwright tests
        run: npx playwright test
        env:
          FINGERTIPS_FRONTEND_URL: ${{ env.url }}

      - uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
