name: Fingertips API Deploy

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Fingertips API Build]
    types:
      - completed
    branches:
      - main

jobs:
  check-db-changes:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_run'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for changes in database directory
        id: check
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^database/'; then
            echo "DB changes detected"
            echo "DB_CHANGED=true" >> $GITHUB_ENV
          else
            echo "No DB changes detected"
            echo "DB_CHANGED=false" >> $GITHUB_ENV
          fi

      - name: Check Database Deployment Status
        uses: actions/github-script@v7
        id: database_status
        if: env.DB_CHANGED == true
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          retries: 3
          script: |
            const runs = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'fingertips-db-deploy.yml',
              head_sha: ${{ github.event.workflow_run.head_branch }},
              status: 'completed'
            });
            core.setOutput("db_completed", runs.data.workflow_runs.length > 0 ? 'true' : 'false');

  determine-version:
    uses: ./.github/workflows/determine-semver.yml
    with:
      fetch-depth: 0
      gitversion-version: "6.0.x"

  api-deploy-development:
    needs: determine-version
    uses: ./.github/workflows/deploy-container.yml
    with:
      tf_state_file_name: fingertips.api.tfstate
      environment: development
      tf_environment: dev
      source_branch: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.head_branch || github.ref_name }}
      source_trigger: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.event || github.event_name }}
      container_image_tag: ${{ github.event_name == 'workflow_run' && format('dhsc.fingertipsnext.api:{0}', needs.determine-version.outputs.sem-ver) || 'dhsc.fingertipsnext.api:latest' }}
      container_name: "fingertips-api"
      revision_suffix: ${{ github.run_number }}
      container_port: 8080
      environment_variables: |
        [
          {
            name        = "DB_SERVER"
            secret_name = "fingertips-sql-hostname"
            value       = null
          },
          {
            name        = "DB_NAME"
            secret_name = "fingertips-db-name"
            value       = null
          },
          {
            name        = "DB_USER"
            secret_name = "fingertips-sql-username"
            value       = null
          },
          {
            name        = "DB_PASSWORD"
            secret_name = "fingertips-sql-password"
            value       = null
          }
        ]
      container_liveness_probe: |
        {
          path      = "/healthcheck"
          port      = 8080
          transport = "HTTP"
        }
    secrets:
      arm-client-id: ${{ secrets.ARM_CLIENT_ID }}
      arm-client-secret: ${{ secrets.ARM_CLIENT_SECRET }}
      arm-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      arm-tenant-id: ${{ secrets.AZURE_TENANT_ID }}

  e2e-tests-development:
    uses: ./.github/workflows/e2e-tests.yml
    if: |
      ${{
        github.event_name == 'workflow_dispatch' ||
        (
          github.event_name == 'workflow_run' &&
          (
            github.event.workflow_run.event == 'push' ||
            github.event.workflow_run.event == 'workflow_dispatch'
          )
        )
      }}
    needs: api-deploy-development
    with:
      env-url: ${{ needs.api-deploy-development.outputs.frontend-dev-url }}
      send-slack-on-fail: "true"
    secrets:
      slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
