name: Fingertips Frontend Deploy

on:
  workflow_run:
    workflows: [Fingertips Frontend Build]
    types:
      - completed
    branches:
      - feature/DHSCFT-208_configure_e2e_tests

jobs:
  determine-version:
    uses: ./.github/workflows/determine-semver.yml
    with:
      fetch-depth: 0
      gitversion-version: "6.0.x"

  frontend-deploy:
    runs-on: ubuntu-latest
    needs: determine-version
    outputs:
      environment_url: ${{ steps.set-url.outputs.url }}
    strategy:
      matrix:
        environment:
          - development
    environment:
      name: ${{ matrix.environment }}
      url: http://4.158.39.145/
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: "Frontend Deploy"
    steps:
      - name: Set environment URL
        id: set-url
        run: echo "url=http://4.158.39.145/" >> $GITHUB_OUTPUT

      - name: Checkout source
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Azure Container Registry Login
        uses: Azure/docker-login@v1
        with:
          username: ${{ secrets.AZURE_CONTAINERREGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_CONTAINERREGISTRY_PASSWORD }}
          login-server: ${{ secrets.AZURE_CONTAINERREGISTRY_SERVER }}

      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          imageToDeploy: "${{ secrets.AZURE_CONTAINERREGISTRY_SERVER }}/dhsc.fingertipsnext.frontend:${{ needs.determine-version.outputs.sem-ver }}"
          containerAppName: fingertips-frontend
          resourceGroup: ${{ vars.RESOURCE_GROUP }}
          containerAppEnvironment: ${{ vars.CONTAINER_APP_ENVIRONMENT }}
          registryUrl: ${{ secrets.AZURE_CONTAINERREGISTRY_SERVER }}
          registryUsername: ${{ secrets.AZURE_CONTAINERREGISTRY_USERNAME }}
          registryPassword: ${{ secrets.AZURE_CONTAINERREGISTRY_PASSWORD }}
          targetPort: 3000
          environmentVariables: "FINGERTIPS_API_URL=${{ vars.FINGERTIPS_API_URL }}"
          azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}
        env:
          AZURE_CONFIG_DIR: $HOME/.azure

  e2e-tests:
    uses: ./.github/workflows/e2e-tests.yml
    needs: frontend-deploy
    with:
      env-url: ${{ needs.frontend-deploy.outputs.environment_url }}
