name: Fingertips Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
    paths:
      - api/**
      - database/fingertips-db/**
      - frontend/fingertips-frontend/**
      - terraform/**
      - search-setup/**
      - trend-analysis/**
  pull_request:
    branches:
      - main
    paths:
      - api/**
      - database/fingertips-db/**
      - frontend/fingertips-frontend/**
      - terraform/**
      - search-setup/**
      - trend-analysis/**

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      db_changed: ${{ steps.check.outputs.db_changed }}
      api_changed: ${{ steps.check.outputs.api_changed }}
      frontend_changed: ${{ steps.check.outputs.frontend_changed }}
      search_changed: ${{ steps.check.outputs.search_changed }}
      trend_analysis_changed: ${{ steps.check.outputs.trend_analysis_changed }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Determine changed files
        id: check
        run: |
          PREVIOUS_SHA=$(git rev-parse HEAD~1)
          echo "Previous commit SHA: $PREVIOUS_SHA"

          if git diff --name-only $PREVIOUS_SHA HEAD | grep '^database/fingertips-db/'; then
            echo "DB changes detected"
            echo "db_changed=true" >> $GITHUB_OUTPUT
          else
            echo "No changes found in DB directory"
            echo "db_changed=false" >> $GITHUB_OUTPUT
          fi

          if git diff --name-only $PREVIOUS_SHA HEAD | grep -E '^api/|^terraform/'; then
            echo "API or Terraform changes detected"
            echo "api_changed=true" >> $GITHUB_OUTPUT
          else
            echo "No relevant changes found in API or Terraform directories"
            echo "api_changed=false" >> $GITHUB_OUTPUT
          fi

          if git diff --name-only $PREVIOUS_SHA HEAD | grep -E '^frontend/fingertips-frontend/|^terraform/'; then
            echo "Frontend or Terraform changes detected"
            echo "frontend_changed=true" >> $GITHUB_OUTPUT
          else
            echo "No relevant changes found in Frontend or Terraform directories"
            echo "frontend_changed=false" >> $GITHUB_OUTPUT
          fi

          if git diff --name-only $PREVIOUS_SHA HEAD | grep -E '^search-setup/'; then
            echo "Search setup changes detected"
            echo "search_changed=true" >> $GITHUB_OUTPUT
          else
            echo "No relevant changes found in search setup directory"
            echo "search_changed=false" >> $GITHUB_OUTPUT
          fi

          if git diff --name-only $PREVIOUS_SHA HEAD | grep -E '^trend-analysis/'; then
            echo "Trend analysis application changes detected"
            echo "trend_analysis_changed=true" >> $GITHUB_OUTPUT
          else
            echo "No relevant changes found in the trend analysis application"
            echo "trend_analysis_changed=false" >> $GITHUB_OUTPUT
          fi

  e2e-and-api-tests:
    needs: [check-changes]
    if: >
      always() &&
      contains(needs.*.result, 'success') &&
      !contains(needs.*.result, 'failure') &&
      !contains(needs.*.result, 'cancelled') &&
      (
        github.event_name == 'workflow_dispatch' ||
        (
          needs.check-changes.outputs.db_changed == 'true' ||
          needs.check-changes.outputs.api_changed == 'true' || 
          needs.check-changes.outputs.frontend_changed == 'true' ||
          needs.check-changes.outputs.search_changed == 'true'
        )
      )
    uses: ./.github/workflows/e2e-and-api-tests.yml
    with:
      environment: dev
      playwright-mode: docker
    secrets:
      fingertips_e2e_db_password: ${{ secrets.FINGERTIPS_E2E_DB_PASSWORD }}
