name: Fingertips Workflow

on:
  workflow_dispatch:
    inputs:
      update_screenshots:
        description: 'Update baseline screenshots'
        required: false
        default: false
        type: boolean

jobs:
  e2e-and-api-tests:
    if: >
      github.event_name == 'workflow_dispatch' &&
      inputs.update_screenshots == true
    uses: ./.github/workflows/e2e-and-api-tests.yml
    with:
      playwright-mode: docker
      update_screenshots: ${{ inputs.update_screenshots }}
    secrets:
      fingertips_e2e_db_password: ${{ secrets.FINGERTIPS_E2E_DB_PASSWORD }}
