name: Update Baseline Screenshots
#test
on:
  workflow_dispatch:
  push:
    branches:
      - 'feature/DHSCFT-715_screenshots_plan_A_B'

jobs:
  update-screenshots:
    name: Update Baseline Screenshots for E2E Tests
    uses: ./.github/workflows/e2e-and-api-tests.yml
    with:
      playwright-mode: docker
      update_screenshots: true
    secrets:
      fingertips_e2e_db_password: ${{ secrets.FINGERTIPS_E2E_DB_PASSWORD }}
